const data = {
  'plants': [
    {'plantNameHeb':'אבוטילון דלי', 'thailand':'อบูติลอน', 'size':'DLI', 'plantNameEng':'ABUTILON'},
    {'plantNameHeb':'אבליה 4L', 'thailand':'อเบเรีย', 'size':'4L', 'plantNameEng':'ABELYA'},
    {'plantNameHeb':'אבליה מגוון 4L', 'thailand':'อเบเรียลาย', 'size':'4L', 'plantNameEng':'ABELYA  MEGUVAN'},
    {'plantNameHeb':'אגבה', 'thailand':'อกาวา', 'size':'DLI', 'plantNameEng':'AGAVA'},
    {'plantNameHeb':'אגפנטוס כחול 4L', 'thailand':'อกาพันตุสม่วง', 'size':'4L', 'plantNameEng':'AGAPANTOS BLUE'},
    {'plantNameHeb':'אגפנטוס לבן 4L', 'thailand':'อกาพันตุสขาว', 'size':'4L', 'plantNameEng':'AGAPANTOS WHITE'},
    {'plantNameHeb':'אוג גלאוקה גודל   3', 'thailand':'โอกอาวกลา', 'size':'3L', 'plantNameEng':'OG GLAUKA'},
    {'plantNameHeb':'אוג גלאוקה גודל 4', 'thailand':'โอกอาวกลา', 'size':'4L', 'plantNameEng':'OG GLAUKA'},
    {'plantNameHeb':'אוג גלאוקה דלי', 'thailand':'โอกอาวก้า', 'size':'DLI', 'plantNameEng':'OG GLAUKA'},
    {'plantNameHeb':'אוג חרוג גודל 3', 'thailand':'โอกคารุก', 'size':'3L', 'plantNameEng':'OG CHARUG'},
    {'plantNameHeb':'אוג חרוג גודל 4', 'thailand':'โอกคารุก', 'size':'4L', 'plantNameEng':'OG CHARUG'},
    {'plantNameHeb':'אוג חרוג דלי', 'thailand':'โอกคารุก', 'size':'DLI', 'plantNameEng':'OG CHARUG'},
    {'plantNameHeb':'אוג מסולסל גודל', 'thailand':'โอกเมชซูซาน', 'size':'DLI', 'plantNameEng':'OG MESULSAL'},
    {'plantNameHeb':'אוג מסולסל גודל 3', 'thailand':'โอกเมชซูซาน', 'size':'3L', 'plantNameEng':'OG MESULSAL'},
    {'plantNameHeb':'אוג מסולסל גודל 4', 'thailand':'โอกเมชซูซาน', 'size':'4L', 'plantNameEng':'OG MESULSAL'},
    {'plantNameHeb':'אוזן ארי גודל 4', 'thailand':'โอเชนอาริ', 'size':'4L', 'plantNameEng':'OZEN ARI'},
    {'plantNameHeb':'אורנית לוהבת', 'thailand':'ออนิต โลเวท', 'size':'4L', 'plantNameEng':'ORNIT LOHEVET whith flower'},
    {'plantNameHeb':'אורנית לוהבת דלי', 'thailand':'ออนิต โลเวท', 'size':'DLI', 'plantNameEng':'ORNIT LOHEVET whith flower'},
    {'plantNameHeb':'אזוביון מנוצה גודל 4', 'thailand':'อีซอฟยอนเมนูเช่', 'size':'4L', 'plantNameEng':'EZOVYON MENUTSE'},
    {'plantNameHeb':'אזוביון מנצה גודל3', 'thailand':'อีซอฟยอนเมนูเช่', 'size':'3L', 'plantNameEng':'EZOVYON MENUTSE'},
    {'plantNameHeb':'אזוביון משונן 4L', 'thailand':'อิซอฟยอนเมชซูนัน', 'size':'4L', 'plantNameEng':'EZOVYON MESHUNAN'},
    {'plantNameHeb':'אזוביון רפואי גודל 3', 'thailand':'อีซอฟยอนเรฟูอิท', 'size':'3L', 'plantNameEng':'EZOVYON REFUI'},
    {'plantNameHeb':'אזוביון רפואי גודל 4', 'thailand':'อีซอฟยอนเรฟูอิท', 'size':'4L', 'plantNameEng':'EZOVYON REFUI'},
    {'plantNameHeb':'אחירותם החורש גודל 4', 'thailand':'อาชิโรเต็ม', 'size':'4L', 'plantNameEng':'ACHIROTEM ACHORESH'},
    {'plantNameHeb':'אירסין לינדן גודל 4', 'thailand':'อิลิสินลินเดน', 'size':'4L', 'plantNameEng':'IRISIN LINDEN'},
    {'plantNameHeb':'אירסין ססגוני גודל 4', 'thailand':'อิลิสินลินสาสโกนี', 'size':'4L', 'plantNameEng':'IRISIN SASGONI'},
    {'plantNameHeb':'אליוגינה  לבן דלי', 'thailand':'เอลโยกิน่าลาวาน', 'size':'DLI', 'plantNameEng':'ELYOGINA LAVAN'},
    {'plantNameHeb':'אליוגינה סגול דלי', 'thailand':'เอลโยกิน่าสโกล', 'size':'DLI', 'plantNameEng':'ELYOGINA SAGOL'},
    {'plantNameHeb':'אלמון הודי דלי', 'thailand':'อาวมอนโฮดิท', 'size':'DLI', 'plantNameEng':'ALMON HODI'},
    {'plantNameHeb':'אלמנדה צהובה דלי', 'thailand':'อาลันมันดาชโฮพ', 'size':'DLI', 'plantNameEng':'ALAMANDA TSAOV'},
    {'plantNameHeb':'אלמנדה קוניק דלי', 'thailand':'อาลันมันดาโกเหนียก', 'size':'DLI', 'plantNameEng':'ALAMANDA KONYAK'},
    {'plantNameHeb':'אלת המסטיק גודל 4', 'thailand':'ยีราฟมาตติก', 'size':'4L', 'plantNameEng':'ELAT AMASTIK'},
    {'plantNameHeb':"אנג'ולינה ורודה גודל 4", 'thailand':'อันจูลิน่าชมพู', 'size':'4L', 'plantNameEng':'ANJOLINA VRODA  (PINK)'},
    {'plantNameHeb':"אנג'ולינה לבנה גודל 4", 'thailand':'อันจูลิน่าขาว', 'size':'4L', 'plantNameEng':'ANJOLINA LEVANA   (WHITE)'},
    {'plantNameHeb':"אנג'ולינה סגולה גודל 4", 'thailand':'อันจูลิน่าม่วง', 'size':'4L', 'plantNameEng':'ANJOLINA SGULA (VYOLET)'},
    {'plantNameHeb':'אנטיגון דק עוקצים', 'thailand':'อันติกอน', 'size':'DLI', 'plantNameEng':'ANTIGON DAK OKATZIM'},
    {'plantNameHeb':'אספרג מאירי בדלי', 'thailand':'อัสปารักเมรี', 'size':'DLI', 'plantNameEng':'ASPARAG MEIRI'},
    {'plantNameHeb':'אספרג מאירי גודל 4', 'thailand':'อัสปารักเมรี', 'size':'4L', 'plantNameEng':'ASPARAG MEIRI'},
    {'plantNameHeb':'אקורוס צהוב', 'thailand':'อกูลูส', 'size':'4L', 'plantNameEng':'AKOROS'},
    {'plantNameHeb':'אקליפה אדום מגוון', 'thailand':'อการิฟาแดง', 'size':'DLI', 'plantNameEng':'AKALIFA MEGUVAN ADOM'},
    {'plantNameHeb':'אקליפה ירוק מגוון', 'thailand':'อการิฟาเขียว', 'size':'4L', 'plantNameEng':'AKALIFA MEGUVAN YAROK'},
    {'plantNameHeb':'אקליפטוס כדורי', 'thailand':'อกาลิปตุส', 'size':'DLI', 'plantNameEng':'AKALIPTUS KADURI'},
    {'plantNameHeb':'אקליפטוס כדורי גודל 4', 'thailand':'อกาลิปตุส', 'size':'4L', 'plantNameEng':'AKALIPTUS KADURI'},
    {'plantNameHeb':'ארקובית', 'thailand':'อกูบิด', 'size':'3L', 'plantNameEng':'AREKOBIT'},
    {'plantNameHeb':'בוגונויליה מיני תאי בדלי', 'thailand':'โบโกวิเรียมินิไท', 'size':'DLI', 'plantNameEng':'BOGONVILYA MINI TAI'},
    {'plantNameHeb':'בוגונויליה מיני תאי גודל 4', 'thailand':'โบโกวิเรียมินิไท', 'size':'4L', 'plantNameEng':'BOGONVILYA MINI TAI'},
    {'plantNameHeb':'בוהיניה גלפיניה גודל 4', 'thailand':'โบวาเนีย', 'size':'4L', 'plantNameEng':'BOWANIAH GALEBINIH'},
    {'plantNameHeb':'בולבין גודל 4', 'thailand':'บุลบิน', 'size':'4L', 'plantNameEng':'BOLBIN'},
    {'plantNameHeb':'בונגונויליה בדלי', 'thailand':'โบโกวิเรียมิก', 'size':'DLI', 'plantNameEng':'BOGONVILYA (MIX)'},
    {'plantNameHeb':'בונגונויליה מיקס גודל 4', 'thailand':'โบโกวิเรียมิก', 'size':'4L', 'plantNameEng':'BOGONVILYA  MIX'},
    {'plantNameHeb':'בזיליקום (ריחן)', 'thailand':'บาชิริกุม', 'size':'4L', 'plantNameEng':'BAZILIKUM'},
    {'plantNameHeb':'בחר מוצר', 'thailand':'', 'size':'', 'plantNameEng':''},
    {'plantNameHeb':'ביפי גודל 4', 'thailand':'บิฟฟิ', 'size':'4L', 'plantNameEng':'BIFI'},
    {'plantNameHeb':'ביפי דלי', 'thailand':'บิฟฟิ', 'size':'DLI', 'plantNameEng':'BIFI'},
    {'plantNameHeb':'ביצן  מגוון ננסי גודל 3', 'thailand':'บิซานเมกูวานนานาซี', 'size':'3L', 'plantNameEng':'BITSAN  MEGUVAN NANASI'},
    {'plantNameHeb':'ביצן  מגוון ננסי גודל 4', 'thailand':'บิซานเมกูวานนานาซี', 'size':'4L', 'plantNameEng':'BITSAN  MEGUVAN NANASI'},
    {'plantNameHeb':'ביצן אוסטרלי גודל 3', 'thailand':'บิซานโอตาลี', 'size':'3L', 'plantNameEng':'BITSAN OSTRALI'},
    {'plantNameHeb':'ביצן אוסטרלי גודל 4', 'thailand':'บิซานโอตาลี', 'size':'4L', 'plantNameEng':'BITSAN OSTRALI'},
    {'plantNameHeb':'ביצן טריקולור גודל 4', 'thailand':'บิซานติโกโล', 'size':'4L', 'plantNameEng':'BITSAN TRIKOLOR'},
    {'plantNameHeb':'ביצן ננסי - רובי  גודל 4', 'thailand':'บิซานอูบีนานาซี', 'size':'4L', 'plantNameEng':'BITSAN RUBI NANASI'},
    {'plantNameHeb':'ביצן רובי גודל 4', 'thailand':'บิซานอูบี', 'size':'4L', 'plantNameEng':'BITSAN RUBI'},
    {'plantNameHeb':"בכריס פיג'נט פוינט גודל 3", 'thailand':'บัคกรีดพิเจนพอย', 'size':'3L', 'plantNameEng':'BACHRIS PIJGENT POINT'},
    {'plantNameHeb':"בכריס פיג'נט פוינט גודל 4", 'thailand':'บัคกรีดพิเจนพอย', 'size':'4L', 'plantNameEng':'BACHRIS PIJGENT POINT'},
    {'plantNameHeb':'בלמקנדה גודל 4', 'thailand':'บารามกานดา', 'size':'4L', 'plantNameEng':'BALAMKANDA'},
    {'plantNameHeb':'במבוק ננסי גודל 4', 'thailand':'บามบุกนานาซี', 'size':'4L', 'plantNameEng':'BAMBOK NANASI'},
    {'plantNameHeb':'במבוק ננסי מגוון גודל 4', 'thailand':'บามบุกนานาซีเมกกูวาน', 'size':'4L', 'plantNameEng':'BAMBOK NANASI MEGOVAN'},
    {'plantNameHeb':'בן אלוי קטן עלים גודל 4', 'thailand':'เบนนาอย', 'size':'4L', 'plantNameEng':'BEN ALOY KTAN ALIM'},
    {'plantNameHeb':'בן אפר מכחיל גודל 4', 'thailand':'เบนอฟา', 'size':'4L', 'plantNameEng':'BEN AFAR MAKCHIL'},
    {'plantNameHeb':'בן עוזרר הודי גודל 3', 'thailand':'เบนนูซ่าโอดิ', 'size':'3L', 'plantNameEng':'BEN UZRAR HODI'},
    {'plantNameHeb':'בן עוזרר הודי גודל 4', 'thailand':'เบนนูซ่าโอดิ', 'size':'4L', 'plantNameEng':'BEN UZRAR HODI'},
    {'plantNameHeb':'בן עוזרר הודי דלי', 'thailand':'เบนนูซ่าโอดิ', 'size':'DLI', 'plantNameEng':'BEN UZRAR HODI'},
    {'plantNameHeb':'בן עוזרר סוככני גודל 3', 'thailand':'เบนนูซ่าซาคาซานี', 'size':'3L', 'plantNameEng':'BEN UZRAR SOCHECHANI'},
    {'plantNameHeb':'בן עוזרר סוככני גודל 4', 'thailand':'เบนนูซ่าซาคาซานี', 'size':'4L', 'plantNameEng':'BEN UZRAR SOCHECHANI'},
    {'plantNameHeb':'בן עוזרר סוככני דלי', 'thailand':'เบนนูซ่าซาคาซานี', 'size':'DLI', 'plantNameEng':'BEN UZRAR SOCHECHANI'},
    {'plantNameHeb':'בראליה גודל 3', 'thailand':'บาเรเรีย', 'size':'3L', 'plantNameEng':'BARELIA'},
    {'plantNameHeb':'ברברית יפנית ארגמנית', 'thailand':'เบอเบอริทยาปานี', 'size':'4L', 'plantNameEng':'BERBERIT YAPANIT ARGEMANIT'},
    {'plantNameHeb':'ברונפלסיה  גזע 25', 'thailand':'บรอนเฟรนเสียเกสา', 'size':'25L', 'plantNameEng':'BRONFELSIYA GEZA 25'},
    {'plantNameHeb':'ברונפלסיה  גזע דלי', 'thailand':'บรอนเฟรนเสียเกสา', 'size':'DLI', 'plantNameEng':'BRONFELSIYA GEZA'},
    {'plantNameHeb':'ברונפלסיה בוש בדלי', 'thailand':'บอรนเฟนเซียบุช', 'size':'DLI', 'plantNameEng':'BRONFELSYA BUSH'},
    {'plantNameHeb':'ברונפלסיה גודל 4', 'thailand':'บอนเฟนเซีย', 'size':'4L', 'plantNameEng':'BRONFELSYA'},
    {'plantNameHeb':'ברוש אפור דלי (סטריקטה)', 'thailand':'บอสอะฟลอ', 'size':'DLI', 'plantNameEng':'BROSH AFOR (hispanika)'},
    {'plantNameHeb':'ברוש טוטם     50ליטר', 'thailand':'บอสโตเต็ม', 'size':'25L', 'plantNameEng':'BROSH TOTEM'},
    {'plantNameHeb':'ברוש טוטם  25ליטר', 'thailand':'บอสโตเต็ม', 'size':'25L', 'plantNameEng':'BROSH TOTEM'},
    {'plantNameHeb':'ברוש טוטם דלי', 'thailand':'บอสโตเต็ม', 'size':'DLI', 'plantNameEng':'BROSH TOTEM'},
    {'plantNameHeb':'ברוש טויה דלי', 'thailand':'บอสโตยา', 'size':'DLI', 'plantNameEng':'BROSH TOYA'},
    {'plantNameHeb':'ברוש לימוני דלי', 'thailand':'บอสลิโมนี', 'size':'DLI', 'plantNameEng':'BROSH LIMONI'},
    {'plantNameHeb':'ברכינטון', 'thailand':'บราคิตอล', 'size':'25L', 'plantNameEng':'BRACHINTON'},
    {'plantNameHeb':'ברכינטון', 'thailand':'บราคิมตอล', 'size':'DLI', 'plantNameEng':'BRACHINTON'},
    {'plantNameHeb':'ברכינטון חשוף שורש', 'thailand':'บราคิตอลซูฟโชริช', 'size':'DLI', 'plantNameEng':'BRACHINTON CHASUF SHORESH'},
    {'plantNameHeb':'ברניה אדומה מנוקדת', 'thailand':'บารีเนียแดง', 'size':'4L', 'plantNameEng':'BRENYA ADUMA MENUKEDET'},
    {'plantNameHeb':'ברניה אדומה מנוקדת  דלי', 'thailand':'บาริเนียอะโดม', 'size':'DLI', 'plantNameEng':'BRENYA ADUMA MENUKEDET'},
    {'plantNameHeb':'ברניה מושלגת 4', 'thailand':'บารีเนียเขียว', 'size':'4L', 'plantNameEng':'BRENYA mushleget'},
    {'plantNameHeb':'ברניה מושלגת בדלי', 'thailand':'บราลิเนียมุชเลเกท', 'size':'DLI', 'plantNameEng':'BRENYA MUSHLEGET'},
    {'plantNameHeb':'ברניה ננסית', 'thailand':'บาริเนียนานาชี', 'size':'', 'plantNameEng':''},
    {'plantNameHeb':'בת אביב ארגמני', 'thailand':'บัทอาวีฟ', 'size':'DLI', 'plantNameEng':'BAT AVIV ARGAMANI'},
    {'plantNameHeb':'בת אביב ארגמני גודל 4', 'thailand':'บัตอาวีฟ', 'size':'4L', 'plantNameEng':'BAT AVIV ARGAMANI'},
    {'plantNameHeb':'בת עופרית גודל 4', 'thailand':'บัทออฟฟิต', 'size':'4L', 'plantNameEng':'BAT AHOFERIT'},
    {'plantNameHeb':'גאורה  לבן גודל 3', 'thailand':'กาวาชมพู', 'size':'3L', 'plantNameEng':'GAURA  LAVAN'},
    {'plantNameHeb':'גאורה ורודה גודל 3', 'thailand':'กาวาชมพู', 'size':'3L', 'plantNameEng':'GAURA VAROD'},
    {'plantNameHeb':'גאורה ורודה גודל 4', 'thailand':'กาวาชมพู', 'size':'4L', 'plantNameEng':'GAURA VAROD'},
    {'plantNameHeb':'גאורה לבנה גודל 4', 'thailand':'กาวาลาวาน', 'size':'4L', 'plantNameEng':'GAURA LAVAN'},
    {'plantNameHeb':'גבגון טווינקל פינק גודל 4', 'thailand':'กัฟนูนชมพู', 'size':'4L', 'plantNameEng':'GAVNUN TWINKEL PINK'},
    {'plantNameHeb':'גבנון בן אזוב לבן גודל 4', 'thailand':'กัฟนูนขาว', 'size':'4L', 'plantNameEng':'GAVNUN BEN EZOV LAVAN'},
    {'plantNameHeb':'גבנון בן אזוב סגול גודל 4', 'thailand':'กัฟนูนม่วง', 'size':'4L', 'plantNameEng':'GAVNUN BEN EZOV SEGOL (violet)'},
    {'plantNameHeb':'גבנון טורפדו גודל 4', 'thailand':'กัฟนูโตปิโด', 'size':'4L', 'plantNameEng':'GAVNUN TORPEDO'},
    {'plantNameHeb':'גבנון קטן קוטרת גודל 4', 'thailand':'กัฟนูนกะตันโกเตเรท', 'size':'4L', 'plantNameEng':'GAVNUN KTAN KOTERET'},
    {'plantNameHeb':'גויאבה תותית', 'thailand':'กูยาวาตูติต', 'size':'DLI', 'plantNameEng':'GUYAVA TUTIT'},
    {'plantNameHeb':'גויבה תותית', 'thailand':'กูยาวาตูติต', 'size':'4L', 'plantNameEng':'GUYAVA TUTIT'},
    {'plantNameHeb':'גומא ננסי גודל 4', 'thailand':'โกเมนนานาซี', 'size':'4L', 'plantNameEng':'GOME NANASI'},
    {'plantNameHeb':'גזניה גודל 4', 'thailand':'กาซาเนีย', 'size':'4L', 'plantNameEng':'GEZANIYA'},
    {'plantNameHeb':'געדה גודל 3', 'thailand':'กาชตา', 'size':'3L', 'plantNameEng':'GAHADA'},
    {'plantNameHeb':'געדה גודל 4', 'thailand':'กาชตา', 'size':'4L', 'plantNameEng':'GEADA'},
    {'plantNameHeb':'גפן בדלי', 'thailand':'กีเฟน', 'size':'DLI', 'plantNameEng':'GEFEN'},
    {'plantNameHeb':'גרדניה  גזע ע. 12', 'thailand':'กาดิเนียร์เกสา', 'size':'POT 12', 'plantNameEng':'GARDENIA  GEZA'},
    {'plantNameHeb':'גרדניה  גזע בדלי', 'thailand':'กาดิเนียร์เกสา', 'size':'DLI', 'plantNameEng':'GARDENIA  GEZA'},
    {'plantNameHeb':'גרדניה בדלי', 'thailand':'กาดิเนียร์', 'size':'DLI', 'plantNameEng':'GARDENIA'},
    {'plantNameHeb':'גרדניה ע. 12', 'thailand':'กาดิเนียร์', 'size':'POT 12', 'plantNameEng':'GARDENIA'},
    {'plantNameHeb':'גרדניה קונ. 17', 'thailand':'กาดิเนียร์', 'size':'POT 17', 'plantNameEng':'GARDENIA (with flower)'},
    {'plantNameHeb':'גרמית לבנה גודל 4', 'thailand':'กาตมิตขาว', 'size':'4L', 'plantNameEng':'GARMIT LAVAN'},
    {'plantNameHeb':'גרמית סגולה גודל 3', 'thailand':'กาตมิตม่วง', 'size':'3L', 'plantNameEng':'GARMIT SAGOL'},
    {'plantNameHeb':'גרמית סגולה גודל 4', 'thailand':'กาตมิตม่วง', 'size':'4L', 'plantNameEng':'GARMIT SAGOL'},
    {'plantNameHeb':'גרניום זוחל', 'thailand':'กิลันยุม', 'size':'4L', 'plantNameEng':'GERANIYUM ZOHEL'},
    {'plantNameHeb':'גרניום לימוני גודל 3', 'thailand':'กิลันยุมลิโมนี', 'size':'3L', 'plantNameEng':'GERANYUM LIMONI'},
    {'plantNameHeb':'גרניום לימוני גודל 4', 'thailand':'กิลันยุมลิโมนี', 'size':'4L', 'plantNameEng':'GERANIYUM LIMONI'},
    {'plantNameHeb':'גת בדלי', 'thailand':'กาท', 'size':'DLI', 'plantNameEng':'GAT'},
    {'plantNameHeb':'דודנאה דנה', 'thailand':'โดโดเนีย', 'size':'DLI', 'plantNameEng':'DODONEA'},
    {'plantNameHeb':'דודנאה דנה גודל 4', 'thailand':'โดโดเนีย', 'size':'4L', 'plantNameEng':'DODONEA'},
    {'plantNameHeb':"דורנטה גולד איג'", 'thailand':'ตุลันดาโกลเอจ', 'size':'DLI', 'plantNameEng':'DORANTA GOLD EIG'},
    {'plantNameHeb':"דורנטה גולד איג' גודל 4", 'thailand':'ตุลันดาโกลเอจ', 'size':'4L', 'plantNameEng':'DORANTA GOLD EIG'},
    {'plantNameHeb':'דורנטה גזע מגוון', 'thailand':'ตุลันดาลายเกสา', 'size':'DLI', 'plantNameEng':'DURANTA GEZA  MEGOVAN'},
    {'plantNameHeb':'דורנטה גזע מרוקו גודל 4', 'thailand':'ตุลันดามาโลโก้', 'size':'DLI', 'plantNameEng':'DURANTA GEZA  MAROKO'},
    {'plantNameHeb':'דורנטה גישה גזע בדלי', 'thailand':'ตุลันดาม่วง', 'size':'DLI', 'plantNameEng':'DORANTA GEYISHA(sagol) GEZA'},
    {'plantNameHeb':'דורנטה גישה לבן גודל 4', 'thailand':'ตูลันดาขาว', 'size':'4L', 'plantNameEng':'DORANTA GEYSHA   (LAVAN) WHITE'},
    {'plantNameHeb':'דורנטה גישה סגול בדלי', 'thailand':'ตุลันดาม่วง', 'size':'DLI', 'plantNameEng':'DORANTA GEYISHA(sagol) VIOLET'},
    {'plantNameHeb':'דורנטה גישה סגול גודל 4', 'thailand':'ตุลันดาม่วง', 'size':'4L', 'plantNameEng':'DORANTA GEYSHA   (sagol) VIOLET'},
    {'plantNameHeb':'דורנטה לבן בדלי', 'thailand':'ตูลันดาขาว', 'size':'DLI', 'plantNameEng':'DORANTA  (LAVAN) WHITE FLOWER'},
    {'plantNameHeb':'דורנטה בוש מגוון', 'thailand':'ตุลันดาลายบูช', 'size':'DLI', 'plantNameEng':'DURANTA  MEGOVAN'},
    {'plantNameHeb':'דורנטה מגוונת גודל 4', 'thailand':'ตุลันดาเมกกูวาน', 'size':'4L', 'plantNameEng':'DORANTA MEGOVENET'},
    {'plantNameHeb':'דורנטה פרמידה בדלי', 'thailand':'ตุลันดาแหลม', 'size':'DLI', 'plantNameEng':'DURANTA PERAMIDA'},
    {'plantNameHeb':'דורנטה בוש מרוקו בדלי', 'thailand':'ตุลันดามาโลโก้บูช', 'size':'DLI', 'plantNameEng':'DORANTA MAROKO'},
    {'plantNameHeb':'דורנטה תילאנדית גודל 3', 'thailand':'ตุลันดาไทยแลนดิท', 'size':'3L', 'plantNameEng':'DORANTA TAILANDIT'},
    {'plantNameHeb':'דורנטה תילאנדית גודל 4', 'thailand':'ตุลันดาไทยแลนดิท', 'size':'4L', 'plantNameEng':'DORANTA TAILANDIT'},
    {'plantNameHeb':'דורנטה תילאנדית דלי', 'thailand':'ตุลันดาไทยแลนดิท', 'size':'DLI', 'plantNameEng':'DORANTA TAILANDIT'},
    {'plantNameHeb':'דיאטס גרנדי פלורה בדלי', 'thailand':'ไดยาเต็ดแกรนฟลอร่า', 'size':'DLI', 'plantNameEng':'DIATES GRANDIFLORA'},
    {'plantNameHeb':'דיאטס גרנדי פלורה גודל 4', 'thailand':'ไดยาเต็ดแกรนฟลอร่า', 'size':'4L', 'plantNameEng':'DAYTES GRANDIFLORA'},
    {'plantNameHeb':'דיאטס דו גווני בדלי', 'thailand':'ไดยาเต็ดดูกูนี', 'size':'DLI', 'plantNameEng':'DIATES DU GONI'},
    {'plantNameHeb':'דיאטס דו גווני גודל 4', 'thailand':'ไดยาเต็ดดูกูนี', 'size':'4L', 'plantNameEng':'DAYTES DU GONI'},
    {'plantNameHeb':'דיאנלה מגוונת', 'thailand':'เดียเนียล่าเมกกูวาน', 'size':'DLI', 'plantNameEng':'DIANELLA MEGOVENET'},
    {'plantNameHeb':'דיאנלה מגוונת גודל 4', 'thailand':'เดียเนียล่าเมกกูวาน', 'size':'4L', 'plantNameEng':'DIANELLA MEGOVENET'},
    {'plantNameHeb':'דיאסקיה גודל 4', 'thailand':'เดียอัสเกีย', 'size':'4L', 'plantNameEng':'DIASKIYA'},
    {'plantNameHeb':'דיכונדרה מכסיפה', 'thailand':'ดิโคนดา มาชิฟา', 'size':'3L', 'plantNameEng':'DICHONDRA'},
    {'plantNameHeb':'דיכונדרה מכסיפה', 'thailand':'ดิโคนดา มาชิฟา', 'size':'4L', 'plantNameEng':'DICHONDRIA'},
    {'plantNameHeb':'דיפלדניה  גודל 4', 'thailand':'ดิฟฟาเดเนีย', 'size':'4L', 'plantNameEng':'DIPLADENIYA'},
    {'plantNameHeb':'דיפלדניה אדום', 'thailand':'ดิฟฟาเดเนีย', 'size':'DLI', 'plantNameEng':'DIPLADENIA RED'},
    {'plantNameHeb':'דיפלדניה ורוד', 'thailand':'ดิฟฟาเดเนีย', 'size':'DLI', 'plantNameEng':'DIPLADENIA pink'},
    {'plantNameHeb':'דיפלדניה לבן', 'thailand':'ดิฟฟาเดเนีย', 'size':'DLI', 'plantNameEng':'DIPLADENIA with'},
    {'plantNameHeb':'דם המכבים', 'thailand':'ดามฮามากาบิม', 'size':'DLI', 'plantNameEng':'DAM HAMAKABIM'},
    {'plantNameHeb':'דם המכבים גודל 4', 'thailand':'ดามฮามากาบิม', 'size':'4L', 'plantNameEng':'DAM HAMAKABIM'},
    {'plantNameHeb':'דק פרי כתום 10L', 'thailand':'ดากปริส้ม', 'size':'DLI', 'plantNameEng':'DAK PRI KATOM'},
    {'plantNameHeb':'דק פרי כתום 3L', 'thailand':'ดากปริส้ม', 'size':'3L', 'plantNameEng':'DAK PRI KATOM'},
    {'plantNameHeb':'דק פרי כתום 4L', 'thailand':'ดากปริส้ม', 'size':'4L', 'plantNameEng':'DAK PRI KATOM'},
    {'plantNameHeb':'דק פרי צהוב', 'thailand':'ดากปริเหลือง', 'size':'4L', 'plantNameEng':'DAK PRI TSAHOV'},
    {'plantNameHeb':'דקל אריקה', 'thailand':'เดกเคนเอนริกา', 'size':'25L', 'plantNameEng':'DEKEL ERIKA'},
    {'plantNameHeb':'דקל אריקה בדלי', 'thailand':'เดกเคนเอนริกา', 'size':'DLI', 'plantNameEng':'DEKEL ERIKA'},
    {'plantNameHeb':'דקל חמדוראה דלי', 'thailand':'เดกเคนคามาโดเรีย', 'size':'DLI', 'plantNameEng':'DEKEL CHAMADOREA'},
    {'plantNameHeb':'דקל טבעות 50 ליטר', 'thailand':'เดกเคนโตบาโอด', 'size':'25L', 'plantNameEng':'DEKEL TABAOT'},
    {'plantNameHeb':'דקל טבעות יחיד', 'thailand':'เดกเคนโตบาโอด', 'size':'25L', 'plantNameEng':'DEKEL TABAOT YEHID'},
    {'plantNameHeb':'דקל טבעות יחיד  25 ליטר', 'thailand':'เดกเคนโตบาโอด1ต้น', 'size':'25L', 'plantNameEng':'DEKEL TABAOT  (one geza)'},
    {'plantNameHeb':'דקל טבעות שלשיה', 'thailand':'เดกเคนโตบาโอดชิชียา', 'size':'25L', 'plantNameEng':'DEKEL TABAOT SLISHIYA'},
    {'plantNameHeb':'דקל טבעות שלשיה 25 ליטר', 'thailand':'เดกเคนโตบาโอดชิชิเยีย', 'size':'25L', 'plantNameEng':'DEKEL TABAOT SLISHIYA'},
    {'plantNameHeb':'דקל טורסאי', 'thailand':'เดกเคนโตไช', 'size':'25L', 'plantNameEng':'DEKEL TORSAI'},
    {'plantNameHeb':'דקל משולש', 'thailand':'เดกเคนเมชูลาช', 'size':'25L', 'plantNameEng':'DEKEL MESHOLASH'},
    {'plantNameHeb':'דקל משולש בדלי', 'thailand':'เดกเคนเมชูลาช', 'size':'DLI', 'plantNameEng':'DEKEL MESHULASH'},
    {'plantNameHeb':'דקל רוביליני', 'thailand':'เดกเคนโตบาโอดอูบิลินี', 'size':'25L', 'plantNameEng':'DEKEL RUBILINI'},
    {'plantNameHeb':'דקל רוביליני זוג', 'thailand':'เดกเคนโตบาโอดอูบิลินี', 'size':'25L', 'plantNameEng':'DEKEL RUBILINI 2 GEZA'},
    {'plantNameHeb':'דקל רוביליני יחיד', 'thailand':'เดกเคนโตบาโอดอูบิลินี', 'size':'25L', 'plantNameEng':'DEKEL RUBILINI 1 GEZA'},
    {'plantNameHeb':'דקל רוביליני שלישיה', 'thailand':'เดกเคนโตบาโอดอูบิลินี', 'size':'25L', 'plantNameEng':'DEKEL RUBILINI 3 GEZA'},
    {'plantNameHeb':'דקל שמרופס', 'thailand':'เดกเคนโตบาโอดชามาโรพ', 'size':'25L', 'plantNameEng':'DEKEL SHEMAROPS'},
    {'plantNameHeb':'דרדר חסוף פרי 4L', 'thailand':'ดาดาฮาชุปี้', 'size':'4L', 'plantNameEng':'DARDAR HASUF PRI'},
    {'plantNameHeb':'דרדר מאפיר', 'thailand':'ดาดามาเฟีย', 'size':'DLI', 'plantNameEng':'DARDAR MAFIR'},
    {'plantNameHeb':'דרדר מאפיר גודל 4', 'thailand':'ดาดามาเฟีย', 'size':'4L', 'plantNameEng':'DARDAR MAHAFIR'},
    {'plantNameHeb':'דרדר מאפיר דלי', 'thailand':'ดาดามาเฟีย', 'size':'DLI', 'plantNameEng':'DARDAR MAFIR'},
    {'plantNameHeb':'דרצנה אוסטרלית  בדלי אדום', 'thailand':'ดรัชไชน่าโอตาริอะโดม', 'size':'DLI', 'plantNameEng':'DRATSENA OSTRALIT- RED'},
    {'plantNameHeb':'דרצנה אוסטרלית בדלי ירוק', 'thailand':'ดรัชไชน่าชิชิโยทยาโรก', 'size':'DLI', 'plantNameEng':'DRATSENA OSTRALIT- GREEN'},
    {'plantNameHeb':'דרצנה שלישיות בדלי ירוק', 'thailand':'ดรัชไชน่าชิชิโยทยาโรก', 'size':'DLI', 'plantNameEng':'DRATSENA SHLISHIYOT- GREEN'},
    {'plantNameHeb':'דרצנה שלישיות בדלי מגוון', 'thailand':'ดรัชไชน่าชิชิโยทยาโรก', 'size':'DLI', 'plantNameEng':'DRATSENA SHLISHIYOT- MEGOVAN'},
    {'plantNameHeb':'הביסקוס סורי גודל4', 'thailand':'ฮิบิสกุสซูรี', 'size':'4L', 'plantNameEng':'HIBISKUS SURI MIX'},
    {'plantNameHeb':'הדס טרנטיני גודל 3', 'thailand':'อาดาสมัซซุย....', 'size':'3L', 'plantNameEng':'HADAS TARANTINI'},
    {'plantNameHeb':'הדס טרנטיני גודל 4', 'thailand':'อาดาสตาลันตินี', 'size':'4L', 'plantNameEng':'HADAS TARANTINI'},
    {'plantNameHeb':'הדס טרנטיני גודל 4', 'thailand':'อาดาสตาลันตินี', 'size':'4L', 'plantNameEng':'HADAS TARANTINI'},
    {'plantNameHeb':'הדס כדור', 'thailand':'อาดาสเกสากลม', 'size':'DLI', 'plantNameEng':'HADAS GEZA BALL'},
    {'plantNameHeb':'הדס כדור  12', 'thailand':'อาดาสเกสากลม', 'size':'POT 12', 'plantNameEng':'HADAS GEZA BALL'},
    {'plantNameHeb':"הדס כדור גזע 25 ל'", 'thailand':'อาดาสเกสากลม', 'size':'25L', 'plantNameEng':'HADAS GEZA (BALL)'},
    {'plantNameHeb':'הדס כדור גזע. 17', 'thailand':'อาดาสเกสากลม', 'size':'POT 17', 'plantNameEng':'HADAS GEZA (BALL)'},
    {'plantNameHeb':'הדס מצוי גודל 3', 'thailand':'อาดาสมัซซุย', 'size':'3L', 'plantNameEng':'HADAS MATSUI'},
    {'plantNameHeb':'הדס מצוי גודל 4', 'thailand':'อาดาสมัสซุย', 'size':'4L', 'plantNameEng':'HADAS MATSUI'},
    {'plantNameHeb':'הדס פונפונים 25 ליטר', 'thailand':'อาดาสเกสากลมปอนปอนิม', 'size':'25L', 'plantNameEng':'HADAS PONPONIM'},
    {'plantNameHeb':'הדס פירמידה 25 ליטר', 'thailand':'อาดาสแหลม', 'size':'25L', 'plantNameEng':'HADAS PIRAMIDA'},
    {'plantNameHeb':'הדס פירמידה בדלי', 'thailand':'อาดาแหลม', 'size':'DLI', 'plantNameEng':'HADAS PIRAMIDA'},
    {'plantNameHeb':'הדס פרמידה 12', 'thailand':'อาดาสแหลม', 'size':'POT 12', 'plantNameEng':'HADAS PIRAMIDA'},
    {'plantNameHeb':'הדס פרמידה 17', 'thailand':'อาดาสแหลม', 'size':'POT 17', 'plantNameEng':'HADAS PIRAMIDA'},
    {'plantNameHeb':'היביסקוס מגוון גודל 4', 'thailand':'ฮิบิสกุสเมกกูวาน', 'size':'4L', 'plantNameEng':'HIBISKUS MEGOVAN'},
    {'plantNameHeb':'היביסקוס סורי דלי', 'thailand':'ฮิบิสกุสสูเรีย', 'size':'DLI', 'plantNameEng':'HEBISKUS SURI'},
    {'plantNameHeb':'היביסקוס סורי מיקס  קונ. 4', 'thailand':'ฮิบิสกุสสุรี', 'size':'4L', 'plantNameEng':'HIBISKUS SURI MIX'},
    {'plantNameHeb':'היביסקוס סיני מיקס גודל 4', 'thailand':'ฮิบิสกุสซินิมิก', 'size':'4L', 'plantNameEng':'HIBISKUS SINI MIX'},
    {'plantNameHeb':'היביסקוס סתריה  4', 'thailand':'ฮิบิสกุสสัสตาเรีย', 'size':'4L', 'plantNameEng':'HIBISKUS SATARIA'},
    {'plantNameHeb':'היבסקוס אדום', 'thailand':'ฮิบิสกุสเกสาอะโดม', 'size':'4L', 'plantNameEng':'HIBISKUS RED'},
    {'plantNameHeb':'היבסקוס בוש אדום דלי', 'thailand':'ฮิบิสกุสบุช', 'size':'DLI', 'plantNameEng':'HIBISKUS BUSH RED'},
    {'plantNameHeb':'היבסקוס מיקס גזע  דלי', 'thailand':'ฮิบิสกุสเกสามิกซ์', 'size':'DLI', 'plantNameEng':'HIBISKUS GEZA MIX'},
    {'plantNameHeb':'היבסקוס בוש דלי', 'thailand':'ฮิบิสกุสบุช', 'size':'DLI', 'plantNameEng':'HIBISKUS BUSH MIX'},
    {'plantNameHeb':'היבסקוס גזע  דלי', 'thailand':'ฮิบิสกุสเกสามิกซ์', 'size':'DLI', 'plantNameEng':'HIBISKUS GEZA MIX'},
    {'plantNameHeb':'היבסקוס גזע אדום דלי', 'thailand':'ฮิบิสกุสเกสาอะโดม', 'size':'DLI', 'plantNameEng':'HIBISKUS GEZA RED'},
    {'plantNameHeb':'היבסקוס גזע אדום קונ. 17', 'thailand':'ฮิบิสกุสเกสาอะโดม', 'size':'POT 17', 'plantNameEng':'HIBISKUS GEZA RED'},
    {'plantNameHeb':'היבסקוס גזע מיקס קונ. 17', 'thailand':'ฮิบิสกุสเกสามิกซ์', 'size':'POT 17', 'plantNameEng':'HIBISKUS GEZA MIX'},
    {'plantNameHeb':'היבסקוס מגוון דלי', 'thailand':'ฮิบิชกุสลาย', 'size':'DLI', 'plantNameEng':'HIBISKUS MEGOVAN'},
    {'plantNameHeb':'היבסקוס סטריה 25 ליטר', 'thailand':'ฮีบิสกุส สัสตาเรีย', 'size':'25L', 'plantNameEng':'HIBISKUS SATARIA'},
    {'plantNameHeb':'היבסקוס סטריה דלי', 'thailand':'ฮิบิสกุสสัสตาเรีย', 'size':'DLI', 'plantNameEng':'HIBISKUS SATARIA'},
    {'plantNameHeb':'המופיליה', 'thailand':'ฮอโมฟีเรีย', 'size':'DLI', 'plantNameEng':'HEMOFILYA'},
    {'plantNameHeb':'המליה בדלי', 'thailand':'ฮาเมเรีย', 'size':'DLI', 'plantNameEng':'HAMELYA'},
    {'plantNameHeb':'המליה גודל 3', 'thailand':'ฮาเมเรีย', 'size':'3L', 'plantNameEng':'HAMELIYA'},
    {'plantNameHeb':'המליה גודל 4', 'thailand':'ฮาเมเรีย', 'size':'4L', 'plantNameEng':'HAMELIYA'},
    {'plantNameHeb':'המרקוליס צהוב גודל 4', 'thailand':'ฮามเมโลโกลิส', 'size':'4L', 'plantNameEng':'HAMEROKOLIS'},
    {'plantNameHeb':'הרדוף', 'thailand':'ฮัมดุบ', 'size':'DLI', 'plantNameEng':'HARDUF'},
    {'plantNameHeb':'הרדוף', 'thailand':'ฮัมดุบ', 'size':'4L', 'plantNameEng':'HARDUF'},
    {'plantNameHeb':'ויטידניה אוסטרלית גודל 3', 'thailand':'วิดทิดเดเนีย', 'size':'3L', 'plantNameEng':'VITIDENIYA OSTRALIT'},
    {'plantNameHeb':'וירבנה ארגנטינאית גודל 4', 'thailand':'เวอบินา', 'size':'4L', 'plantNameEng':'VEREBENA  AREGENTINAIT'},
    {'plantNameHeb':'ורבנה ארגנטינאית גודל 4', 'thailand':'เวอบินา', 'size':'4L', 'plantNameEng':'VERBENA  ARGENTINAIT'},
    {'plantNameHeb':'ורד איסברג - לבן גודל 4', 'thailand':'เวเรดไอเบิก', 'size':'4L', 'plantNameEng':'VERED ISBERG white rose'},
    {'plantNameHeb':'ורד ח-2 אדום גודל 4', 'thailand':'เวเรอะโดมเคชไต', 'size':'4L', 'plantNameEng':'VERED (RED ROSE)'},
    {'plantNameHeb':'ורדים כילאי-תה אדום גודל 4', 'thailand':'เวเรดกิเรียดอะโดม', 'size':'4L', 'plantNameEng':'VERED (rose) red'},
    {'plantNameHeb':'ורדים כילאי-תה ורוד  גודל 4', 'thailand':'เวเรดชมพู', 'size':'4L', 'plantNameEng':'VERED (rose) pink'},
    {'plantNameHeb':'ורדים כילאי-תה כתום  גודל 4', 'thailand':'เวเรดส้ม', 'size':'4L', 'plantNameEng':'VERED (rose) orange'},
    {'plantNameHeb':'ורדים כילאי-תה צהוב גודל 4', 'thailand':'เวเรดเหลือง', 'size':'4L', 'plantNameEng':'VERED (rose)  yellow'},
    {'plantNameHeb':'ורדים כילאי תה בורדו  גודל 4', 'thailand':'เวเรดบูดู', 'size':'4L', 'plantNameEng':'VERED (rose) bordo'},
    {'plantNameHeb':'ורדים כילאי תה לבן גודל 4', 'thailand':'กเวเรดขาว', 'size':'4L', 'plantNameEng':'VERED (rose) white'},
    {'plantNameHeb':'זאתר', 'thailand':'ชาตา', 'size':'4L', 'plantNameEng':'ZATAR'},
    {'plantNameHeb':'זוטה', 'thailand':'ชูตา', 'size':'3L', 'plantNameEng':'ZUTA'},
    {'plantNameHeb':'זוטה', 'thailand':'ชูตา', 'size':'4L', 'plantNameEng':'ZUTA'},
    {'plantNameHeb':'זיף נוצה  ירוק גודל 4', 'thailand':'ซิฟโนซ่ายาโรค', 'size':'4L', 'plantNameEng':'ZIF NOTSA YAROK'},
    {'plantNameHeb':'זיף נוצה ארגמני בדלי', 'thailand':'ซิฟโนซ่าอเกมานี', 'size':'DLI', 'plantNameEng':'ZIF NOTSA ARGEMANI'},
    {'plantNameHeb':'זיף נוצה ארגמני גודל 4', 'thailand':'ซิฟโนซ่าอเกมานี', 'size':'4L', 'plantNameEng':'ZIF NOTSA ARGEMANI'},
    {'plantNameHeb':'זיף נוצה זנב שועל גודל 4', 'thailand':'<ซิฟโนซ่ายาโรค<', 'size':'4L', 'plantNameEng':'ZIF NOTSA ZNAV SHUAL'},
    {'plantNameHeb':'זית על גזע - 25 ליטר', 'thailand':'ซาอิทเกสา', 'size':'25L', 'plantNameEng':'ZAIT GEZA'},
    {'plantNameHeb':'זית עציץ 17', 'thailand':'สติม', 'size':'POT 17', 'plantNameEng':'ZAI  - GEZA KATAN'},
    {'plantNameHeb':'חבושית גודל 4', 'thailand':'ฮาบูชิด', 'size':'4L', 'plantNameEng':'HABOOSET'},
    {'plantNameHeb':'חבלבל מאוריטני גודל 3', 'thailand':'คาวานวาน', 'size':'3L', 'plantNameEng':'CHAVALVAL mauritani'},
    {'plantNameHeb':'חבלבל מאוריטני גודל 4', 'thailand':'คาวานวาน', 'size':'4L', 'plantNameEng':'CHAVALVAL mauritani'},
    {'plantNameHeb':'חיצית הטיפין', 'thailand':'คาชิด อธิพิน', 'size':'DLI', 'plantNameEng':'CHITSIT ATIPIN'},
    {'plantNameHeb':'חלבלוב קוצני דלי', 'thailand':'ฮาลาลูโกซานิ', 'size':'DLI', 'plantNameEng':'HALAVLUV KOTSANI'},
    {'plantNameHeb':'חרצית גודל 4', 'thailand':'คัสซิส', 'size':'4L', 'plantNameEng':'CHARTSIT MIX'},
    {'plantNameHeb':'חרציתן מאפיר', 'thailand':'คาซิตันมาเฟีย', 'size':'DLI', 'plantNameEng':'CHARTSITAN MAAFIR'},
    {'plantNameHeb':'חרציתן מאפיר גודל 3', 'thailand':'คาซิตันมาเฟีย', 'size':'3L', 'plantNameEng':'CHARTSITAN MAAFIR'},
    {'plantNameHeb':'חרציתן מאפיר גודל 4', 'thailand':'คาซิตันมาเฟีย', 'size':'4L', 'plantNameEng':'CHARTSITAN MAAFIR'},
    {'plantNameHeb':'טברמונטנה דלי', 'thailand':'ตาเบอบอนตานา', 'size':'DLI', 'plantNameEng':'TABERMONTANA'},
    {'plantNameHeb':'טגטס לימוני גודל 4', 'thailand':'ไตยาเต็ตลิมูนี', 'size':'4L', 'plantNameEng':'TAGETES LIMONI'},
    {'plantNameHeb':'טולבגיה לבנה גודל 4', 'thailand':'ตูนเบเกียขาว', 'size':'4L', 'plantNameEng':'TULBEGYA LAVAN'},
    {'plantNameHeb':'טולבגיה מגוונת גודל 4', 'thailand':'ตูนเบเกียลาย', 'size':'4L', 'plantNameEng':'TULBEGYA  - meguvenet'},
    {'plantNameHeb':'טולבגיה סגולה גודל 4', 'thailand':'ตูนเบเกียม่วง', 'size':'4L', 'plantNameEng':'TULBEGYA SAGOL'},
    {'plantNameHeb':'טונברגיה מטפס סגול דלי', 'thailand':'ตูนเบเกียมิตาเปตสโกล', 'size':'DLI', 'plantNameEng':'TUNBERGYA METAPES SAGOL'},
    {'plantNameHeb':'טונברגיה שיחית דלי', 'thailand':'ตูนเบเกียมิต', 'size':'DLI', 'plantNameEng':'TUNBERGYA BUSH'},
    {'plantNameHeb':'טיבוצינה  גודל 4', 'thailand':'ติบุชชน่าอาลิกตัน', 'size':'4L', 'plantNameEng':'TIBOTSHINA ALE KATAN'},
    {'plantNameHeb':'טיבוצינה עלה גדול דלי', 'thailand':'ติบุชชน่าอาลิกโดน', 'size':'DLI', 'plantNameEng':'TIBOTSHINA ALE GADOL'},
    {'plantNameHeb':'טיבוצינה עלה קטן דלי', 'thailand':'ติบุชไชน่าอาริกตัน', 'size':'DLI', 'plantNameEng':'TIBOTSHINA ALE KATAN'},
    {'plantNameHeb':'טלמון גודל 4', 'thailand':'เทวมอน', 'size':'4L', 'plantNameEng':'TALMON'},
    {'plantNameHeb':'טרכלוספרמון יסמיני', 'thailand':'มะลิฝอย', 'size':'DLI', 'plantNameEng':'TRACHLOSFERMON YASMINI'},
    {'plantNameHeb':'טרכלוספרמון יסמיני גודל 3', 'thailand':'มะลิฝอย', 'size':'3L', 'plantNameEng':'TRACHLOSFERMON YASMINI'},
    {'plantNameHeb':'טרכלוספרמון יסמיני גודל 4', 'thailand':'มะลิฝอย', 'size':'4L', 'plantNameEng':'TRACHLOSFERMON YASMINI'},
    {'plantNameHeb':'יהודי נודד גודל 4', 'thailand':'ยูดิโนเด็ด', 'size':'4L', 'plantNameEng':'YEHUDI NODED'},
    {'plantNameHeb':'יוקה', 'thailand':'ยุกะ', 'size':'DLI', 'plantNameEng':'YOKA'},
    {'plantNameHeb':'יטרופה מולטיפידה גזע 25L', 'thailand':'ยาโตรปะมุลติฟิดา', 'size':'25L', 'plantNameEng':'YATROPA MULTIFIDA GEZA'},
    {'plantNameHeb':'יטרופה מולטיפידה גזע דלי', 'thailand':'ยาโตรปะมุลติฟิดา', 'size':'DLI', 'plantNameEng':'YATROPA MULTIFIDA GEZA'},
    {'plantNameHeb':'יטרופה תמימה דלי', 'thailand':'ยาโตปะทิมา', 'size':'DLI', 'plantNameEng':'YATROPA TMIMA'},
    {'plantNameHeb':'יסמין אור  דלי', 'thailand':'มะลิเขียว', 'size':'DLI', 'plantNameEng':'YASMIN OR'},
    {'plantNameHeb':'יסמין אור קונ. 17', 'thailand':'มะลิเขียว', 'size':'POT 17', 'plantNameEng':'YASMIN OR'},
    {'plantNameHeb':'יסמין אזורי דלי', 'thailand':'มะลิน้อย', 'size':'DLI', 'plantNameEng':'YASMIN AZURI'},
    {'plantNameHeb':'יסמין אזורי קונ. 17', 'thailand':'มะลิน้อย', 'size':'POT 17', 'plantNameEng':'YASMIN AZURI'},
    {'plantNameHeb':'יסמין סמבק דלי', 'thailand':'ยัสมินซัมบัค', 'size':'DLI', 'plantNameEng':'YASMIN SAMBAK'},
    {'plantNameHeb':'יסמין סמבק קונ. 17', 'thailand':'มะลิขาว', 'size':'POT 17', 'plantNameEng':'YASMIN SAMBAK'},
    {'plantNameHeb':'יסמין פול מצרי  דלי', 'thailand':'มะลิใหญ่', 'size':'DLI', 'plantNameEng':'YASMIN FUL (mitsri)'},
    {'plantNameHeb':'יסמין פול מצרי קונ. 17', 'thailand':'มะลิใหญ่', 'size':'POT 17', 'plantNameEng':'YASMIN FUL (mitsri)'},
    {'plantNameHeb':'יסמין צהוב דלי', 'thailand':'มะลิเหลือง', 'size':'DLI', 'plantNameEng':'YASMIN TSAHOV'},
    {'plantNameHeb':'יסמין צהוב קונ. 17', 'thailand':'มะลิเหลือง', 'size':'POT 17', 'plantNameEng':'YASMIN  (YELOEW)'},
    {'plantNameHeb':'יערה אקרוטית', 'thailand':'ยารากุติ', 'size':'4L', 'plantNameEng':'YAARA AKRUTIT'},
    {'plantNameHeb':'ירקה', 'thailand':'ยากา', 'size':'3L', 'plantNameEng':'YWREKA'},
    {'plantNameHeb':'ישמונית', 'thailand':'จัตโมนิต', 'size':'4L', 'plantNameEng':'YASMONIT'},
    {'plantNameHeb':'כנפופיה', 'thailand':'คันฟูฟินยา', 'size':'4L', 'plantNameEng':'KANEPOPIYA'},
    {'plantNameHeb':'כסיה סוככנית', 'thailand':'ก๊าซเซียโสคัคคานี', 'size':'3L', 'plantNameEng':'KASIYA SOCHECHANIT'},
    {'plantNameHeb':'כסיה סוככנית', 'thailand':'ก๊าซเซียโสคัคคานี', 'size':'4L', 'plantNameEng':'KASIYA SOCHECHANIT'},
    {'plantNameHeb':'כריך הושימה מגוון 4', 'thailand':'คาริลาย', 'size':'4L', 'plantNameEng':'KARI  HOSIENA MEGOVAN'},
    {'plantNameHeb':'לואיזה גודל 4', 'thailand':'ลูอิซ่า', 'size':'4L', 'plantNameEng':'LUIZA'},
    {'plantNameHeb':'לוגוסטרום ירוק בדלי', 'thailand':'โลกุสตูมยาโรค', 'size':'DLI', 'plantNameEng':'LOGOSTRUM YAROK'},
    {'plantNameHeb':'לוגוסטרום ירוק גודל 4', 'thailand':'โลกุสตูมยาโรค', 'size':'4L', 'plantNameEng':'LOGOSTRUM YAROK'},
    {'plantNameHeb':'לוגוסטרום מגוון', 'thailand':'โลกุสตูมเมกกูวาน', 'size':'DLI', 'plantNameEng':'LOGOSTRUM MEGUVAN'},
    {'plantNameHeb':'לוגוסטרום מגוון גודל 4', 'thailand':'โลกุสตูมเมกกูวาน', 'size':'4L', 'plantNameEng':'LOGOSTRUM MEGUVAN'},
    {'plantNameHeb':'לוגוסטרמיה בוש  בדלי', 'thailand':'โลโกสเตเมียบูช', 'size':'DLI', 'plantNameEng':'LOGOSTREMYA BUSH'},
    {'plantNameHeb':'לוגוסטרמיה גודל 4', 'thailand':'โลโกสเตเมีย', 'size':'4L', 'plantNameEng':'LOGOSTREMYA'},
    {'plantNameHeb':'לוגוסטרמיה גזע  בדלי', 'thailand':'โลโกเตเมียเกสา', 'size':'DLI', 'plantNameEng':'LOGOSTREMYA GEZA'},
    {'plantNameHeb':'לוטם שעיר', 'thailand':'โรเต็มสะอิว', 'size':'4L', 'plantNameEng':'LOTEM  SAIR'},
    {'plantNameHeb':'לוטם מרווני', 'thailand':'โรเต็มมาวานิ', 'size':'4L', 'plantNameEng':'LOTEM MARVANI'},
    {'plantNameHeb':'לוקפליום גרין קלאוד גודל 3', 'thailand':'โลโกฟินยมกรีนเค้า', 'size':'3L', 'plantNameEng':'LOKOFILYUM GREEN KLAOUD'},
    {'plantNameHeb':'לוקפליום גרין קלאוד גודל 4', 'thailand':'โลโกฟินยมกรีนเค้า', 'size':'4L', 'plantNameEng':'LOKOFILYUM GREEN KLAOUD'},
    {'plantNameHeb':'לוקפליום סן חוזה גודל 4', 'thailand':'โลโกฟินยมซานโคเซ', 'size':'4L', 'plantNameEng':'LOKOFILYUM SAN HOZE'},
    {'plantNameHeb':'לוקפליום קומפקטי דלי', 'thailand':'โลโกฟินยมคอมปาติ', 'size':'DLI', 'plantNameEng':'LOKOFILYUM KOMPAKTI'},
    {'plantNameHeb':'לוקפליום קומפקטי גודל 3', 'thailand':'โลโกฟินยมคอมปาติ', 'size':'3L', 'plantNameEng':'LOKOFILYUM KOMPAKTI'},
    {'plantNameHeb':'לוקפליום קומפקטי גודל 4', 'thailand':'โลโกฟินยมคอมปาติ', 'size':'4L', 'plantNameEng':'LOKOFILYUM KOMPAKTI'},
    {'plantNameHeb':'לוקפליום סילבר קלאוד גודל 4', 'thailand':'โลโกฟินยมชิเวอเค้า', 'size':'4L', 'plantNameEng':'LOKOFILYUM SILVER KLAUD'},
    {'plantNameHeb':"לירופה גרין ג'ייאנט", 'thailand':'ไลโยป้ากินคาดานิท', 'size':'DLI', 'plantNameEng':'LARIYOPA GREEN GIANT'},
    {'plantNameHeb':'לירופה גרין גינט גודל 4', 'thailand':'ไลโยป้ากินไจแอน', 'size':'4L', 'plantNameEng':'LARIYOPA GRIN GAJENT'},
    {'plantNameHeb':'לירופה כדנית גודל 4', 'thailand':'ไลโยป้ากินคาดานิท', 'size':'4L', 'plantNameEng':'LARIYOPA KADANIT'},
    {'plantNameHeb':'לנטנה לבנה גודל 3', 'thailand':'ลันตานาขาว', 'size':'3L', 'plantNameEng':'LANTANA LEVANA'},
    {'plantNameHeb':'לנטנה לבנה גודל 4', 'thailand':'ลันตานาขาว', 'size':'4L', 'plantNameEng':'LANTANA LEVANA'},
    {'plantNameHeb':'לנטנה סגולה גודל 3', 'thailand':'ลันตานาม่วง', 'size':'3L', 'plantNameEng':'LANTANA SGULA (lilachit)'},
    {'plantNameHeb':'לנטנה סגולה גודל 4', 'thailand':'ลันตานาม่วง', 'size':'4L', 'plantNameEng':'LANTANA SGULA (lilachit)'},
    {'plantNameHeb':'לנטנה ססגונית צהו/כתום גודל 4', 'thailand':'ลันตานาเหลือง/ส้ม', 'size':'4L', 'plantNameEng':'LANTANA SASGONIT (yelow/orang)'},
    {'plantNameHeb':'לנטנה צהובה גודל 3', 'thailand':'ลันตานาเหลือง', 'size':'3L', 'plantNameEng':'LANTANA yellow'},
    {'plantNameHeb':'לנטנה רדיאיישן אדום גודל 3', 'thailand':'ลันตานาแดง/ส้ม', 'size':'3L', 'plantNameEng':'LANTANA RADIAISHEN (red/orang)'},
    {'plantNameHeb':'לנטנה רדיאיישן אדום גודל 4', 'thailand':'ลันตานาแดง/ส้ม', 'size':'4L', 'plantNameEng':'LANTANA RADIAISHEN (red/orang)'},
    {'plantNameHeb':'לנטנה רדיאיישן ננסי גודל 4', 'thailand':'ลันตานานานานชี', 'size':'4L', 'plantNameEng':'LANTANA RADIAISHEN NANASI'},
    {'plantNameHeb':'לנטנה רדיאיישן ננסי מגוון גודל 4', 'thailand':'ลันตานานานาชีลาย', 'size':'4L', 'plantNameEng':'LANTANA RADIAISHEN  NANASI MEGUVAN'},
    {'plantNameHeb':'לענה לואיזיאנית גודל 4', 'thailand':'ลาฮานา', 'size':'4L', 'plantNameEng':'LAHANA LUIZIANIT'},
    {'plantNameHeb':'מאוג ימי  גודל 3', 'thailand':'มาโอค', 'size':'4L', 'plantNameEng':'MHAOG YAMI'},
    {'plantNameHeb':'מולנברגיה גודל 4', 'thailand':'มูลเบเกีย', 'size':'4L', 'plantNameEng':'MULENBERGYA'},
    {'plantNameHeb':'מונרדה מצויה גודל 4', 'thailand':'โมนาดาเมซซุยาน', 'size':'4L', 'plantNameEng':'MONARDA METSUYA'},
    {'plantNameHeb':'מוראה מכבדית', 'thailand':'โมเรีย', 'size':'DLI', 'plantNameEng':'MOREA MICHBADIT'},
    {'plantNameHeb':'מוראה מכבדית', 'thailand':'โมเรีย', 'size':'4L', 'plantNameEng':'MOREA MICHBADIT'},
    {'plantNameHeb':'מורן החורש', 'thailand':'โมลาน', 'size':'DLI', 'plantNameEng':'MORAN HAHORESH'},
    {'plantNameHeb':'מורן החורש גודל 4', 'thailand':'โมลาน', 'size':'4L', 'plantNameEng':'MORAN HAHORESH'},
    {'plantNameHeb':'מטרוסידרוס אפור 25 ליטר', 'thailand':'เมโตร เทา', 'size':'25L', 'plantNameEng':'METROS AFOR'},
    {'plantNameHeb':'מטרוסידרוס אפור גודל 4', 'thailand':'เมโตร เทา', 'size':'4L', 'plantNameEng':'METROS AFOR'},
    {'plantNameHeb':'מטרוסידרוס אפור דלי', 'thailand':'เมโตรเทา', 'size':'DLI', 'plantNameEng':'METROS AFOR'},
    {'plantNameHeb':'מטרוסידרוס אפור ע. 12', 'thailand':'เมโตร เทา', 'size':'POT 12', 'plantNameEng':'METROS AFOR'},
    {'plantNameHeb':'מטרוסידרוס ירוק דלי', 'thailand':'เมโตรเขียว', 'size':'DLI', 'plantNameEng':'METROS YAROK'},
    {'plantNameHeb':'מטרוסידרוס ירוק ע. 12', 'thailand':'เมโตรยาโรค', 'size':'POT 12', 'plantNameEng':'METROS YAROK'},
    {'plantNameHeb':'מטרוסידרוס מגוון דלי', 'thailand':'เมโตรลาย', 'size':'DLI', 'plantNameEng':'METROS MEGUVAN'},
    {'plantNameHeb':'מטרוסידרוס מגוון ע. 12', 'thailand':'เมโตรเมกกูวาน', 'size':'POT 12', 'plantNameEng':'METROS MEGOVAN'},
    {'plantNameHeb':'מטרוסידרוס תומפסון 25 ליטר', 'thailand':'เมโตรเขียว', 'size':'25L', 'plantNameEng':'METROS TOMPSON (green)'},
    {'plantNameHeb':'מיופורום ביצני גודל 4', 'thailand':'เมียวฟอยุมบิชานิ', 'size':'4L', 'plantNameEng':'MIYOFOROM BITSANI'},
    {'plantNameHeb':'מיופורום גודל 3', 'thailand':'เมียวฟอยุม กานาลิม', 'size':'3L', 'plantNameEng':'MIYOFOROM'},
    {'plantNameHeb':'מיופורום גודל 4', 'thailand':'เมียวฟอยุม กานาลิม', 'size':'4L', 'plantNameEng':'MIYOFOROM'},
    {'plantNameHeb':'מילניס סוואנה גודל 3', 'thailand':'มิลินิต', 'size':'3L', 'plantNameEng':'MILENIS SAVANA'},
    {'plantNameHeb':'מילניס סוואנה גודל 4', 'thailand':'มิลินิต', 'size':'4L', 'plantNameEng':'MILENIS SAVANA'},
    {'plantNameHeb':'מיסקנטוס ירוק גודל 4', 'thailand':'มิสกันตุสเขียว', 'size':'4L', 'plantNameEng':'MISKANTUS YAROK'},
    {'plantNameHeb':'מיסקנטוס מגוון גודל 4', 'thailand':'มิสกันตุสเมกกูวาน', 'size':'4L', 'plantNameEng':'MISKANTUS MEGOVAN'},
    {'plantNameHeb':'מלוח גודל 4', 'thailand':'มัดลวก', 'size':'4L', 'plantNameEng':'MALUACH'},
    {'plantNameHeb':'מלוליקה גולד  גזע  דלי', 'thailand':'เมโลไลก้าทองเกสา', 'size':'DLI', 'plantNameEng':'MELOLAIKA GOLD GEZA'},
    {'plantNameHeb':'מלוליקה גולד פרמידה דלי', 'thailand':'เมโลไลก้าทองแหลม', 'size':'DLI', 'plantNameEng':'MELOLAIKA GOLD PERAMIDA'},
    {'plantNameHeb':'מלוליקה גולד ע. 12', 'thailand':'เมโลไลก้าทอง', 'size':'POT 12', 'plantNameEng':'MELOLAIKA GOLD'},
    {'plantNameHeb':'מלוליקה קלרט גזע דלי', 'thailand':'เมโลไลก้าคาเล็ท', 'size':'DLI', 'plantNameEng':'MELOLAIKA KLARET GEZA'},
    {'plantNameHeb':'מלוליקה קלרט ע. 12', 'thailand':'เมโลไลก้าคาเล็ท', 'size':'POT 12', 'plantNameEng':'MELOLAIKA KLARET'},
    {'plantNameHeb':'מלפורה ארגמנית גודל 4', 'thailand':'เมลาฟอล่า', 'size':'4L', 'plantNameEng':'MELAFORA ARGEMANIT'},
    {'plantNameHeb':'מנדוילה ורודה', 'thailand':'มัลดิวิล่าชมพู', 'size':'DLI', 'plantNameEng':'MANDEVILA VAROD (PINK)'},
    {'plantNameHeb':'מנדוילה לבנה', 'thailand':'มัลดิวิล่าขาว', 'size':'DLI', 'plantNameEng':'MANDEVILA LAVAN (WHITE)'},
    {'plantNameHeb':'מנדוילה צהובה', 'thailand':'มัลดิวิล่าเหลือง', 'size':'DLI', 'plantNameEng':'MANDEVILA TSAOV (YELOEW)'},
    {'plantNameHeb':'מרבה חלב (פוליגלה) גודל 4', 'thailand':'มาบีชาลาฟ', 'size':'4L', 'plantNameEng':'MARBE CHALAV poligala'},
    {'plantNameHeb':'מרווה אדומה גודל 4', 'thailand':'มาวาแดง', 'size':'4L', 'plantNameEng':'MARVA ADOMA RED'},
    {'plantNameHeb':'מרווה אינדיגו גודל 4', 'thailand':'มาดววาอินดิโก้', 'size':'4L', 'plantNameEng':'MARVA ENDIGO'},
    {'plantNameHeb':'מרווה -הוט ליפס גודל 4', 'thailand':'มาดวาฮอตลิป', 'size':'4L', 'plantNameEng':'MARVA HOT LIPS'},
    {'plantNameHeb':'מרווה גרג גודל  3', 'thailand':'มาดวาเล็ก', 'size':'3L', 'plantNameEng':'MARVA GREG'},
    {'plantNameHeb':'מרווה גרג גודל 4', 'thailand':'มาดวาเล็ก', 'size':'4L', 'plantNameEng':'MARVA GREG'},
    {'plantNameHeb':'מרווה צחורה גודל 3', 'thailand':'มาดวาคูล่า', 'size':'3L', 'plantNameEng':'MARVA TSHORA'},
    {'plantNameHeb':'מרווה צחורה גודל 4', 'thailand':'มาดวาคูล่า', 'size':'4L', 'plantNameEng':'MARVA TSHORA'},
    {'plantNameHeb':'מרווה רפואית גודל 3', 'thailand':'มาดว่าเรฟูอี', 'size':'3L', 'plantNameEng':'MARVA REFUIT'},
    {'plantNameHeb':'מרווה רפואית גודל 4', 'thailand':'มาดว่าเรฟูอี', 'size':'4L', 'plantNameEng':'MARVA REFUIT'},
    {'plantNameHeb':'נולינה ארוכת עלים בדלי', 'thailand':'โนรินา', 'size':'DLI', 'plantNameEng':'NOLINA ARUKAT ALIM'},
    {'plantNameHeb':'ננדינה פאייר בול גודל 4', 'thailand':'นานดินา', 'size':'4L', 'plantNameEng':'NANDINA FAYER BALL'},
    {'plantNameHeb':'סביון מלבין', 'thailand':'ซัฟยอนมัลบิน', 'size':'DLI', 'plantNameEng':'SAVYON MALBIN'},
    {'plantNameHeb':'סביון מלבין גודל 3', 'thailand':'ซัฟยอนมัลบิน', 'size':'3L', 'plantNameEng':'SAVYON MALBIN'},
    {'plantNameHeb':'סביון מלבין גודל 4', 'thailand':'ซัฟยอนมัลบิน', 'size':'4L', 'plantNameEng':'SAVYON MALBIN'},
    {'plantNameHeb':'סולנום', 'thailand':'โสรานุม', 'size':'4L', 'plantNameEng':'SOLANUM'},
    {'plantNameHeb':'סולנום  בוש', 'thailand':'เชกตูมบูช', 'size':'DLI', 'plantNameEng':'SOLANUM BUSH'},
    {'plantNameHeb':'סולנום גזע 17', 'thailand':'โสรานุมเกสา', 'size':'POT 17', 'plantNameEng':'SOLANUM GEZA'},
    {'plantNameHeb':'סולנום גזע 25 ליטר', 'thailand':'โสรานุมเกสา', 'size':'25L', 'plantNameEng':'SOLANUM GEZA'},
    {'plantNameHeb':'סולנום גזע דלי', 'thailand':'โสรานุมเกสา', 'size':'DLI', 'plantNameEng':'SOLANUM GEZA'},
    {'plantNameHeb':'סולנום מטפס בדלי', 'thailand':'โสรานุมมิตาเปต', 'size':'DLI', 'plantNameEng':'SOLANUM METAPES'},
    {'plantNameHeb':'סטיפה גודל 4', 'thailand':'สตีฟา', 'size':'4L', 'plantNameEng':'STIFA'},
    {'plantNameHeb':'סטפנוטיס דלי', 'thailand':'สติฟาโนติส', 'size':'DLI', 'plantNameEng':'STEFANOTIS'},
    {'plantNameHeb':'סיזגיום  בוש בדלי', 'thailand':'ซิซกยุมบูช', 'size':'DLI', 'plantNameEng':'SIZIGYUM  BUHS'},
    {'plantNameHeb':'סיזגיום  פונפונים 25 ליטר', 'thailand':'สิสิยุมปอนปอนิม', 'size':'25L', 'plantNameEng':'SIZGYUM PONPONIM'},
    {'plantNameHeb':'סיזגיום כדור על גזע דלי', 'thailand':'ซิซิกยุมเกสากลม', 'size':'DLI', 'plantNameEng':'SIZIGYUM GEZA (BALL)'},
    {'plantNameHeb':'סיזגיום ספילרה 25 ליטר', 'thailand':'สิสิยุมเกลียว', 'size':'25L', 'plantNameEng':'SIZIGYUM SPIRALA'},
    {'plantNameHeb':'סיזגיום פרמידה 25 ליטר', 'thailand':'สิสิยุมแหลม', 'size':'25L', 'plantNameEng':'SIZGYUM PIRAMIDA'},
    {'plantNameHeb':'סיזגיום פרמידה 50 ליטר', 'thailand':'สซิซิกยุมแหลม', 'size':'50L', 'plantNameEng':'SIZIGYUM PERAMIDA'},
    {'plantNameHeb':'סיזגיום פרמידה בדלי', 'thailand':'ซิซกยุมแหลม', 'size':'DLI', 'plantNameEng':'SIZIGYUM PIRAMIDA'},
    {'plantNameHeb':'סיזיגיום  כדור גזע 25 ליטר', 'thailand':'สิสิยุมเกสากลม', 'size':'25L', 'plantNameEng':'SIZIGYUM GEZA (BALL)'},
    {'plantNameHeb':'סיזיגיום  כדור גזע 50 ליטר', 'thailand':'สิสิยุมเกสากลม', 'size':'50L', 'plantNameEng':'SIZIGYUM GEZA (BALL)'},
    {'plantNameHeb':'סמבוק שחור', 'thailand':'สัมบัคชโคร', 'size':'DLI', 'plantNameEng':'SAMBOK SHAHOR'},
    {'plantNameHeb':'סמבוק שחור גודל 4', 'thailand':'สัมบัคชโคร', 'size':'4L', 'plantNameEng':'SAMBOK SHAHOR'},
    {'plantNameHeb':'סנטולינה  אפורה גודל 4', 'thailand':'ซันตูรีน่าเทา', 'size':'4L', 'plantNameEng':'SANTULINA AFORA'},
    {'plantNameHeb':'סנטולינה  ירוקה גודל 4', 'thailand':'ซันตูรีน่าเขียว', 'size':'4L', 'plantNameEng':'SANTULINA YERUKA'},
    {'plantNameHeb':'ספלול דלי', 'thailand':'ซัฟฟลูล', 'size':'DLI', 'plantNameEng':'SAFLUL'},
    {'plantNameHeb':'סקיבולה גודל 4', 'thailand':'สกีบูลา', 'size':'4L', 'plantNameEng':'SKIVULA'},
    {'plantNameHeb':'עב שיבולת צהוב 4', 'thailand':'อาฟชิโบเล็ตเยลโล', 'size':'4L', 'plantNameEng':'AV SHIBOLET YELLOW'},
    {'plantNameHeb':'עב שיבולת צהוב בדלי', 'thailand':'อาฟชิโบเล็ตเยลโล', 'size':'DLI', 'plantNameEng':'AV SHIBOLET YELLOW'},
    {'plantNameHeb':'עדעד קנרי גודל 4', 'thailand':'อาดอาดกันนารี', 'size':'4L', 'plantNameEng':'ADAD KANARI'},
    {'plantNameHeb':'עופרית הכף לבן גודל 4', 'thailand':'ออฟฟิตขาว', 'size':'4L', 'plantNameEng':'OFRIT AKAF WHITE'},
    {'plantNameHeb':'עופרית הכף כחול  גודל 4', 'thailand':'ออฟฟิตน้ำเงิน', 'size':'4L', 'plantNameEng':'OFRIT AKAF BLUE'},
    {'plantNameHeb':'עינן מסקרני (אריופס)גודל 4', 'thailand':'เอนัน', 'size':'4L', 'plantNameEng':'EINAN MASKARANI'},
    {'plantNameHeb':'עכנאי הדור גודל 4', 'thailand':'อะคาไนคานู', 'size':'4L', 'plantNameEng':'ACHNAI HADUR'},
    {'plantNameHeb':'עכנאי הדור דלי', 'thailand':'อะคาไนคานู', 'size':'DLI', 'plantNameEng':'ACHNAI HADUR'},
    {'plantNameHeb':'עץ אבוקדו', 'thailand':'อาโวกาโด้', 'size':'25L', 'plantNameEng':'ETS AVOKADO (tree)'},
    {'plantNameHeb':'עץ אשכולית לבנה', 'thailand':'เอชโกลิท', 'size':'25L', 'plantNameEng':'ETS ESHKOLIT (tree)'},
    {'plantNameHeb':'עץ גויאבה תותית', 'thailand':'เอช กูยาวาตูติต', 'size':'DLI', 'plantNameEng':'ETS GUYAVA TUTIT (tree)'},
    {'plantNameHeb':'עץ גויאבה תותית', 'thailand':'เอช กูยาวาตูติต', 'size':'25L', 'plantNameEng':'ETS GUYAVA TUTIT (tree)'},
    {'plantNameHeb':'עץ השמן  אפןר', 'thailand':'เอชฮาชเชเมนเทา', 'size':'4L', 'plantNameEng':'ETS HASHEMEN AFOR'},
    {'plantNameHeb':'עץ השמן מגוון 4', 'thailand':'เอชฮาชเชเมนเมกกูวาน', 'size':'4L', 'plantNameEng':'ETS HASHEMEN MEGUVAN'},
    {'plantNameHeb':'עץ לימון', 'thailand':'เอชลิมอน', 'size':'25L', 'plantNameEng':'ETS LIMON (lemon tree)'},
    {'plantNameHeb':'עץ לימון מתוק', 'thailand':'เอชลิมอนมาตุก', 'size':'25L', 'plantNameEng':'ETS LIMON (lemon tree)  MATOK'},
    {'plantNameHeb':'עץ לימון ננסי (לימקוואט)', 'thailand':'เอชลิมขวด', 'size':'25L', 'plantNameEng':'ETS LIMQWAT (limon nanasi)'},
    {'plantNameHeb':'עץ מנגו', 'thailand':'เอชแมงโก', 'size':'25L', 'plantNameEng':'ETS MANGO'},
    {'plantNameHeb':'עץ פומלה', 'thailand':'เอชโพเมลา', 'size':'25L', 'plantNameEng':'ETS POMELA  (tree)'},
    {'plantNameHeb':'עץ פומלית', 'thailand':'เอชโพเมลิท', 'size':'25L', 'plantNameEng':'ETS POMELIT  (tree)'},
    {'plantNameHeb':"עץ פיג'ויה", 'thailand':'เอชฟิโจยา', 'size':'25L', 'plantNameEng':'ETS FIJOYA  (tree)'},
    {'plantNameHeb':'עץ קלמנטינה מיכל', 'thailand':'เอชเครเมนตินา', 'size':'25L', 'plantNameEng':'ETS KLEMANTINA (tree)'},
    {'plantNameHeb':'עץ רימון', 'thailand':'ริมอน', 'size':'25L', 'plantNameEng':'ETS RIMON (tree)'},
    {'plantNameHeb':'עץ שזיף ירוק', 'thailand':'เอชชีซิฟยาโรค', 'size':'25L', 'plantNameEng':'ETS SHEZIF YAROK'},
    {'plantNameHeb':'עץ שזיף פיסארדי', 'thailand':'เอชชีซิปิซาดิ', 'size':'25L', 'plantNameEng':'ETS SHEZIF PISARDI'},
    {'plantNameHeb':'עץ תאנה', 'thailand':'เอชทีนา', 'size':'25L', 'plantNameEng':'ETS TEHENA (tree)'},
    {'plantNameHeb':'עץ תפוז דם', 'thailand':'เอชตาปุสดาม', 'size':'25L', 'plantNameEng':'ETS TAPUZ DAM'},
    {'plantNameHeb':'עץ תפוז וושינגטון', 'thailand':'เอชตาปุวอชิงตัน', 'size':'25L', 'plantNameEng':'ETS TAPUZ washington'},
    {'plantNameHeb':'עץ תפוז סיני (קומקוואט)', 'thailand':'เอชคอมขวด', 'size':'25L', 'plantNameEng':'ETS KOMQWAT (tapuz nanasi)'},
    {'plantNameHeb':'עץ תפוז שמוטי', 'thailand':'เอชตาปุสสามุติ', 'size':'25L', 'plantNameEng':'ETS TAPUZ shamuti'},
    {'plantNameHeb':'עץ תפוח', 'thailand':'เอชแอปเปิ้ล', 'size':'25L', 'plantNameEng':'ETS APPLE'},
    {'plantNameHeb':'ערער גודל 4', 'thailand':'อาอา', 'size':'4L', 'plantNameEng':'HARHAR'},
    {'plantNameHeb':'פודרונאה דלי', 'thailand':'โพรโตรเนีย', 'size':'DLI', 'plantNameEng':'PONDRONEA'},
    {'plantNameHeb':'פוטיניה', 'thailand':'โปรติเนีย', 'size':'4L', 'plantNameEng':'PUTINYA'},
    {'plantNameHeb':'פוטיניה  דלי', 'thailand':'โปรติเนีย', 'size':'DLI', 'plantNameEng':'PUTINYA'},
    {'plantNameHeb':'פורמיום ארגמני בדלי', 'thailand':'ฟอมยุมอาเกมานิ', 'size':'DLI', 'plantNameEng':'FORMYUM ARGEMANI'},
    {'plantNameHeb':'פורמיום ארגמני גודל 4', 'thailand':'ฟอมยุมอาเกมานิ', 'size':'4L', 'plantNameEng':'FORMYUM ARGEMANI'},
    {'plantNameHeb':'פטוספורום ירוק גודל 4', 'thailand':'ปะโตสฟอรุมเขียว(ถั่วดิน)', 'size':'4L', 'plantNameEng':'POTOSFERUM GREEN'},
    {'plantNameHeb':'פטוספורום מגוון גודל 4', 'thailand':'ปะโตสฟอรุมเมกกูวาน', 'size':'4L', 'plantNameEng':'POTOSFERUM MEGUVAN'},
    {'plantNameHeb':'פטוספורום ננסי ירוקי4L', 'thailand':'ปะโตสฟอรุมนานซียาโรค', 'size':'4L', 'plantNameEng':'POTOSFERUM NANASI GREEN'},
    {'plantNameHeb':'פטוספורום ננסי מגוון גודל 4', 'thailand':'ปะโตสฟอรุมนานซีลาย', 'size':'4L', 'plantNameEng':'POTOSFERUM NANASI MEGUVAN'},
    {'plantNameHeb':'פטוספורום ננסי דלי', 'thailand':'ปะโตสฟอรุมนานซียาโรค', 'size':'DLI', 'plantNameEng':'POTOSFERUM NANASI GREEN'},
    {'plantNameHeb':'פיטנה 10L', 'thailand':'ฟินา', 'size':'DLI', 'plantNameEng':'FITNA'},
    {'plantNameHeb':'קסנדו 4L', 'thailand':'ซันนาดู', 'size':'4L', 'plantNameEng':'KSANADU'},
    {'plantNameHeb':'פילכון  זהוב שוליים', 'thailand':'ปินโคนลายขาว', 'size':'DLI', 'plantNameEng':'PILCHON WHITE MEGOVAN'},
    {'plantNameHeb':'פילכון  זהוב שוליים', 'thailand':'ปินโคนลายขาว', 'size':'4L', 'plantNameEng':'PILCHON ZEOV SHULAIM'},
    {'plantNameHeb':'פילכון  ירוק', 'thailand':'ปินโคนเขียว', 'size':'4L', 'plantNameEng':'PILCHON GREEN'},
    {'plantNameHeb':'פילכון מגוון צהוב', 'thailand':'ปินโคนลายเหลือง', 'size':'4L', 'plantNameEng':'PILCHON  YELLOW MEGOVAN'},
    {'plantNameHeb':'פילכון מגוון צהוב דלי', 'thailand':'ปินโคนลายเหลือง', 'size':'DLI', 'plantNameEng':'PILCHON  YELLOW MEGOVAN'},
    {'plantNameHeb':'פיקוס גרין אילנד גזע בדלי', 'thailand':'ฟิกุสกรีนไอแลน', 'size':'DLI', 'plantNameEng':'FIKUS GRIN ILAND GEZA'},
    {'plantNameHeb':'פיקוס גרין אילנד גודל 3', 'thailand':'ฟิกุส(บักเดื่อ)', 'size':'3L', 'plantNameEng':'FIKUS GRIN AILAND'},
    {'plantNameHeb':'פיקוס גרין אילנד גודל 4', 'thailand':'ฟิกุส(บักเดื่อ)', 'size':'4L', 'plantNameEng':'FIKUS GRIN AILAND'},
    {'plantNameHeb':'פיקוס גרין אילנד בוש בדלי', 'thailand':'ฟิกุสกรีนไอแลนบูช', 'size':'DLI', 'plantNameEng':'FIKUS GRIN ILAND BUSH'},
    {'plantNameHeb':'פיריקנטה גודל 4', 'thailand':'ปิลากันตา', 'size':'4L', 'plantNameEng':'PIRIKANTA'},
    {'plantNameHeb':'פלקרנטוס מונה לבנדר גודל 4', 'thailand':'ปาการันตุชโมนาลาเวนเดอ', 'size':'4L', 'plantNameEng':'PLAKARANTUS MONA LAVENDER'},
    {'plantNameHeb':'פלקרנטוס מכסיף', 'thailand':'ปาการันตุสมัคสีฟ', 'size':'4L', 'plantNameEng':'PLAKARATUS MAKESEF'},
    {'plantNameHeb':'פלקרנטוס שפתני גודל 3', 'thailand':'ปาการันตุสซิฟตานี', 'size':'3L', 'plantNameEng':'PLAKARANTUS SIFTANI'},
    {'plantNameHeb':'פלקרנטוס שפתני גודל 4', 'thailand':'ปาการันตุสซิฟตานี', 'size':'4L', 'plantNameEng':'PLAKARANTUSSIFTANI'},
    {'plantNameHeb':'פלקרנטוס מגוון גודל 4', 'thailand':'ปาการันตุสซิฟตานีลาย', 'size':'3L', 'plantNameEng':'PLAKARANTUS MEGUVAN'},
    {'plantNameHeb':'פלרגון אלוני גודל 3', 'thailand':'เปรากอน', 'size':'3L', 'plantNameEng':'PELARGON ALONI'},
    {'plantNameHeb':'פלרגון אלוני גודל 4', 'thailand':'เปรากอน', 'size':'4L', 'plantNameEng':'PELARGON ALONI'},
    {'plantNameHeb':'פנדוראה ירוק 3L', 'thailand':'พันโดเรียยาโรค', 'size':'3L', 'plantNameEng':'PANDOREA YAROK'},
    {'plantNameHeb':'פנדוראה ירוק 10L', 'thailand':'พันโดเรียยาโรค', 'size':'DLI', 'plantNameEng':'PANDOREA YAROK'},
    {'plantNameHeb':'פנדוראה מגוון 10L', 'thailand':'พันโดเรียเมกกูวาน', 'size':'DLI', 'plantNameEng':'PANDOREA MEGOVAN'},
    {'plantNameHeb':'פנדוראה מגוון 3L', 'thailand':'พันโดเรียเมกกูวาน', 'size':'3L', 'plantNameEng':'PANDOREA MEGOVAN'},
    {'plantNameHeb':'פנטס ורוד גודל 4', 'thailand':'เบนตัสชมพู', 'size':'4L', 'plantNameEng':'PENTAS  VAROD'},
    {'plantNameHeb':'פסיפלורה דלי', 'thailand':'ปะสิฟลอรา', 'size':'DLI', 'plantNameEng':'PASIFLORA'},
    {'plantNameHeb':'פסיפלורה קונ. 17', 'thailand':'ปะสิฟลอรา', 'size':'POT 17', 'plantNameEng':'PASIFLORA'},
    {'plantNameHeb':"פפאיה 25 ל'", 'thailand':'มะละกอ', 'size':'25L', 'plantNameEng':'PAPAYA'},
    {'plantNameHeb':'פרח שעווה ירוק בדלי', 'thailand':'เปราชซาวาเกสา', 'size':'DLI', 'plantNameEng':'PERACH SHAAVA GREEN'},
    {'plantNameHeb':'פרח שעווה אדום בדלי', 'thailand':'เปราชซาวาเกสา', 'size':'DLI', 'plantNameEng':'PERACH SHAAVA RED'},
    {'plantNameHeb':'פרח שעווה אדום פרמידה בדלי', 'thailand':'เปราชซาวาแหลม', 'size':'DLI', 'plantNameEng':'PERACH SHAAVA RED  PERAMIDA'},
    {'plantNameHeb':'פרח שעווה גזע בדלי', 'thailand':'เปราชซาวาเกสา', 'size':'DLI', 'plantNameEng':'PERACH SHAAVA GEZA'},
    {'plantNameHeb':'פרח שעווה ע. 12', 'thailand':'ซาวา', 'size':'POT 12', 'plantNameEng':'PERACH SHAAVA'},
    {'plantNameHeb':'פרפרון  דלי', 'thailand':'ปาปารอน', 'size':'DLI', 'plantNameEng':'PARPARON'},
    {'plantNameHeb':"ציפור גן עדן ניקולאי 25 ל'", 'thailand':'ชีโปกานาเดนนิโกลาย', 'size':'25L', 'plantNameEng':'TSIPOR GAN EDEN NIKOLAI'},
    {'plantNameHeb':'ציפור גן עדן ניקולאי 10L', 'thailand':'ชีโปกานาเดนนิโกลาย', 'size':'DLI', 'plantNameEng':'TSIPOR GAN EDEN NIKOLAY'},
    {'plantNameHeb':'ציפור גן עדן רגינה בדלי', 'thailand':'ชีโปกานาเดนเรจินา', 'size':'DLI', 'plantNameEng':'TSIPOR GAN EDEN REGINA'},
    {'plantNameHeb':'ציפור גן עדן רגינה גודל 4', 'thailand':'ชีโปกานาเดนเรจินา', 'size':'4L', 'plantNameEng':'TSIPOR GAN EDEN REGINA'},
    {'plantNameHeb':'ציקס  25 ליטר', 'thailand':'ซีกัส', 'size':'25L', 'plantNameEng':'TSIKAS'},
    {'plantNameHeb':'ציקס  טוריסאי 50 ליטר', 'thailand':'ซีกัส โตไช', 'size':'50 L', 'plantNameEng':'TSIKAS TORISAI'},
    {'plantNameHeb':'ציקס 100 ליטר', 'thailand':'ชีกัส', 'size':'130L', 'plantNameEng':'TSIKAS'},
    {'plantNameHeb':'ציקס 50 ליטר', 'thailand':'ซีกัส', 'size':'50 L', 'plantNameEng':'TSIKAS'},
    {'plantNameHeb':'ציקס דיון דלי', 'thailand':'ซีกัสดิโยน', 'size':'DLI', 'plantNameEng':'TSIKAS DYUN'},
    {'plantNameHeb':'ציקס דלי', 'thailand':'ซีกัส', 'size':'DLI', 'plantNameEng':'TSIKAS'},
    {'plantNameHeb':'צסטרום BUSH דלי', 'thailand':'เชกตูมบูช', 'size':'DLI', 'plantNameEng':'TSESTRUM BUSH'},
    {'plantNameHeb':'צסטרום בוש גודל 4', 'thailand':'เชกตูมบูช', 'size':'4L', 'plantNameEng':'TSESTRUM BUSH'},
    {'plantNameHeb':'צסטרום גזע קונ. 17', 'thailand':'เชกตูมเกสา', 'size':'POT 17', 'plantNameEng':'TSESTRUM GEZA'},
    {'plantNameHeb':'צסטרום על גזע דלי', 'thailand':'เชกตูมเกสา', 'size':'DLI', 'plantNameEng':'TSESTRUM GEZA'},
    {'plantNameHeb':'קורדוטריה', 'thailand':'โกโลเตเลีย', 'size':'4L', 'plantNameEng':'KORDOTERIYA'},
    {'plantNameHeb':'קורדוליין אדום בדלי', 'thailand':'โกโดไล แดง', 'size':'DLI', 'plantNameEng':'KORDOLAYIN (red)'},
    {'plantNameHeb':'קורדוליין מגוןן צהוב  בדלי', 'thailand':'โกโดไลเหลือง', 'size':'DLI', 'plantNameEng':'KORDOLAYIN MEGOVAN YELLOW'},
    {'plantNameHeb':'קטרוסית', 'thailand':'กะโตรซิส', 'size':'4L', 'plantNameEng':'KATROSIT'},
    {'plantNameHeb':'קטרוסית גזע 25 ליטר', 'thailand':'กะโตรซิสเกสา', 'size':'25 L', 'plantNameEng':'KATRUSIT Geza'},
    {'plantNameHeb':'קטרוסית גזע בדלי', 'thailand':'กะโตซิสเกสา', 'size':'DLI', 'plantNameEng':'KATRUSIT'},
    {'plantNameHeb':'קיווי', 'thailand':'กีวี', 'size':'DLI', 'plantNameEng':'KIWI'},
    {'plantNameHeb':'קיסוס ירוק', 'thailand':'กิโสสเขียว', 'size':'3L', 'plantNameEng':'KISOS YAROK'},
    {'plantNameHeb':'קיסוס ירוק', 'thailand':'กิโสสเขียว', 'size':'4L', 'plantNameEng':'KISOS YAROK'},
    {'plantNameHeb':'קיסוס ירוק דלי', 'thailand':'กิโสสเขียว', 'size':'DLI', 'plantNameEng':'KISOS YAROK'},
    {'plantNameHeb':'קיסוס מגוון', 'thailand':'กิโสสเขียวลาย', 'size':'4L', 'plantNameEng':'KISOS  MEGUVAN'},
    {'plantNameHeb':'קלדנדרום אדום בדלי', 'thailand':'กะลาดินดุมอะโดม', 'size':'DLI', 'plantNameEng':'KALADENDROM (red)'},
    {'plantNameHeb':'קלדנדרום לבן בדלי', 'thailand':'กะลาดินดุมลาวาน', 'size':'DLI', 'plantNameEng':'KALADENDROM (white)'},
    {'plantNameHeb':'קליניה גודל 4', 'thailand':'คลิเนีย', 'size':'4L', 'plantNameEng':'KLINYA'},
    {'plantNameHeb':'קליניה  זוחלת גודל 4', 'thailand':'คลิเนีย โชเคเรท', 'size':'3L', 'plantNameEng':'KLINYA ZOCHELET'},
    {'plantNameHeb':'קלסטימון גזע דלי', 'thailand':'คาลิตติมอเกสา', 'size':'DLI', 'plantNameEng':'KALISTEMON GEZA'},
    {'plantNameHeb':"קלסטימון ליטל ג'ון 4", 'thailand':'คาลิตติมอลิเตอจอน', 'size':'4L', 'plantNameEng':'KALISTEMON LITEL JON'},
    {'plantNameHeb':"קלסטימון ליטל ג'ון 10L", 'thailand':'คาลิตติมอลิเตอจอน', 'size':'DLI', 'plantNameEng':'KALISTEMON LITEL JON'},
    {'plantNameHeb':'קמליה', 'thailand':'กาเมเรีย', 'size':'DLI', 'plantNameEng':'KAMELYA'},
    {'plantNameHeb':'קנה הודית', 'thailand':'กานาโฮดิท', 'size':'DLI', 'plantNameEng':'KANA HODIT'},
    {'plantNameHeb':'קנה הודית', 'thailand':'กานาโฮดิท', 'size':'4L', 'plantNameEng':'KANA HODIT'},
    {'plantNameHeb':'קנפופיה גודל 4', 'thailand':'คันฟูฟินยา', 'size':'4L', 'plantNameEng':'KANFUFIYA'},
    {'plantNameHeb':'קסאנאדו', 'thailand':'ซันนาดู', 'size':'4L', 'plantNameEng':'KSANADU'},
    {'plantNameHeb':'קסאנאדו דלי', 'thailand':'ซันนาดู', 'size':'DLI', 'plantNameEng':'KSANADU'},
    {'plantNameHeb':'קסלפיניה גודל 4', 'thailand':'กาซาพิเนีย', 'size':'4L', 'plantNameEng':'KASALPINYA'},
    {'plantNameHeb':'קסלפיניה גזע 18L', 'thailand':'กาซาพิเนีย', 'size':'18L', 'plantNameEng':'KASALPINYA GEZA'},
    {'plantNameHeb':'קפרוזמה גזע', 'thailand':'กะโปสม่าเกสา', 'size':'DLI', 'plantNameEng':'KOPROZMA  GEZA'},
    {'plantNameHeb':'קפרוזמה טריקולור דלי', 'thailand':'กะโปสม่าติโกโล', 'size':'DLI', 'plantNameEng':'KOPROZMA TRIKOLOR'},
    {'plantNameHeb':'קפרוזמה ירוק 10L', 'thailand':'กะโปสม่าเขียว', 'size':'DLI', 'plantNameEng':'KOPROZMA GREEN'},
    {'plantNameHeb':'קפרוזמה מגוון 4', 'thailand':'กะโปม่าเมกกูวาน', 'size':'4L', 'plantNameEng':'KOPROZMA MEGUVAN'},
    {'plantNameHeb':'קפרוזמה מגוון דלי', 'thailand':'กะโปม่าเมกกูวาน', 'size':'DLI', 'plantNameEng':'KOPROZMA MEGUVAN'},
    {'plantNameHeb':'קפרוזמה נחושתית 4', 'thailand':'กะโปสม่าเนชชโติต', 'size':'4L', 'plantNameEng':'KOPROZMA  NECHOSHTIT'},
    {'plantNameHeb':'קפרוזמה נחושתית דלי', 'thailand':'กะโปสม่าเนชชโติต', 'size':'DLI', 'plantNameEng':'KOPROZMA  NECHOSHTIT'},
    {'plantNameHeb':'קרואפסיס  גודל 4', 'thailand':'กรอปซิส', 'size':'4L', 'plantNameEng':'KROAPSIS'},
    {'plantNameHeb':'קריסה גרין קרפט גודל 3', 'thailand':'การิซ่ากรีนกาเป็ท', 'size':'3L', 'plantNameEng':'KARISA GRIN KARPET'},
    {'plantNameHeb':'קריסה גרין קרפט גודל 4', 'thailand':'การิซ่ากรีนกาเป็ท', 'size':'4L', 'plantNameEng':'KARISA GRIN KARPET'},
    {'plantNameHeb':'רואליה ורוד 4L', 'thailand':'โรเอเรียชมพู', 'size':'4L', 'plantNameEng':'ROAELIA  VAROD PINK'},
    {'plantNameHeb':'רואליה סגול  4L', 'thailand':'โรเอเรียม่วง', 'size':'4L', 'plantNameEng':'ROAELIA  SAGOL'},
    {'plantNameHeb':'רואליה לבן  4L', 'thailand':'โรเอเรียขาว', 'size':'4L', 'plantNameEng':'ROAELIA  LAVAN'},
    {'plantNameHeb':'רותם 4L', 'thailand':'โรเต็ม', 'size':'4L', 'plantNameEng':'ROTEM'},
    {'plantNameHeb':'רוזמרין בלו לגון גודל 3', 'thailand':'โรสมารินบูลากุน', 'size':'3L', 'plantNameEng':'ROZMARIN BLU LAGON'},
    {'plantNameHeb':'רוזמרין בלו לגון גודל 4', 'thailand':'โรสมารินบูลากุน', 'size':'4L', 'plantNameEng':'ROZMARIN BLU LAGON'},
    {'plantNameHeb':'רוזמרין זוחל גודל 3', 'thailand':'โรสมารินโวเคน', 'size':'3L', 'plantNameEng':'ROZMARIN ZOCHEL'},
    {'plantNameHeb':'רוזמרין זוחל גודל 4', 'thailand':'โรสมารินโวเคน', 'size':'4L', 'plantNameEng':'ROZMARIN ZOCHEL'},
    {'plantNameHeb':'רוזמרין זנב שועל גודל 3', 'thailand':'โรสมารินชนาปชัว', 'size':'3L', 'plantNameEng':'ROZMARIN ZNAV SHUAL'},
    {'plantNameHeb':'רוזמרין זנב שועל גודל 4', 'thailand':'โรสมารินชนาปชัว', 'size':'4L', 'plantNameEng':'ROZMARIN ZNAV SHUAL'},
    {'plantNameHeb':'רוזמרין זקוף גודל 4', 'thailand':'โรสมารินซาคูฟ', 'size':'4L', 'plantNameEng':'ROZMARIN ZTKUF'},
    {'plantNameHeb':'רוסליה אדומה גודל 3', 'thailand':'โรซีเรียอโดม', 'size':'3L', 'plantNameEng':'ROSELIA ADOMA'},
    {'plantNameHeb':'רוסליה אדומה גודל 4', 'thailand':'โรซีเรียอโดม', 'size':'4L', 'plantNameEng':'ROSELIA ADOMA'},
    {'plantNameHeb':'רוסליה צהובה גודל 4', 'thailand':'โรซีเรียเหลือง', 'size':'4L', 'plantNameEng':'ROSELIA TSEHOBA'},
    {'plantNameHeb':'ריאו דו גוני גודל 4', 'thailand':'ลีโอ', 'size':'4L', 'plantNameEng':'RIO DU GONI'},
    {'plantNameHeb':'רימון ננסי  פרמידה 10L', 'thailand':'รีโมน', 'size':'DLI', 'plantNameEng':'RIMON NASNASI'},
    {'plantNameHeb':'רימון ננסי 4L', 'thailand':'รีโมน', 'size':'4L', 'plantNameEng':'RIMON NASNASI'},
    {'plantNameHeb':'שבטבט גודל 4', 'thailand':'ชวาทวาท', 'size':'4L', 'plantNameEng':'SHVATVAT'},
    {'plantNameHeb':'שיבא 4L', 'thailand':'ชิบา', 'size':'4L', 'plantNameEng':'SHIBA'},
    {'plantNameHeb':'שיח אברהם ארגמני דלי', 'thailand':'เสือคำราม', 'size':'DLI', 'plantNameEng':'SIACH AVRAHAM ARGEMANI'},
    {'plantNameHeb':'שיח אברהם ארגמני גודל 4', 'thailand':'เสือคำราม', 'size':'4L', 'plantNameEng':'SIACH AVRAHAM ARGEMANI'},
    {'plantNameHeb':'שיח אברהם ירוק גודל 4', 'thailand':'เสือคำรามเขียว', 'size':'4L', 'plantNameEng':'SIACH AVRAHAM YAROK'},
    {'plantNameHeb':'שפלרה מגוונת גודל 4', 'thailand':'ชิฟเฟราเมกกูวาน', 'size':'4L', 'plantNameEng':'SHIFLERA MEGOVENET'},
    {'plantNameHeb':'שפלרה מגוונת 10L', 'thailand':'ชิฟเฟล่าเอชซิท', 'size':'DLI', 'plantNameEng':'SHIFLERA MEGUVAN'},
    {'plantNameHeb':'שרך  בוסטון צהוב (פנים) 10L', 'thailand':'ชารากบอสตัน', 'size':'DLI', 'plantNameEng':'SARACH BOSTON (yellow)'},
    {'plantNameHeb':'שרך כיליין קיפח ירוק (חוץ) 10L', 'thailand':'ชารากคิลลิยาย', 'size':'DLI', 'plantNameEng':'SARACH  KILYAN'},
    {'plantNameHeb':'', 'thailand':'', 'size':'', 'plantNameEng':''}
  ],
  'clients': [
    {'hebName':' אורה - חן', 'location':'מושב אורה', 'engName':'ORA'},
    {'hebName':' גינון ונוי - נאווה', 'location':'', 'engName':'NAVA GINUN VENOY'},
    {'hebName':' המשתלה  ', 'location':'ביצרון', 'engName':'HAMASHTELA'},
    {'hebName':' כוכב השרון  ', 'location':' ', 'engName':'   KOCHAV ASHARON SANSAN'},
    {'hebName':'א.ש. גינון ופיתוח', 'location':'', 'engName':'A.S. GINUN UPITUACH'},
    {'hebName':'אבו יוסוף  - אבו גוש', 'location':'', 'engName':'ABU YUSUF'},
    {'hebName':'אביבי - גאליה', 'location':'', 'engName':'AVIVI'},
    {'hebName':'אביקם בר שלום', 'location':'', 'engName':'AVIKAM BAR SHALOM'},
    {'hebName':'אבני חיים -אמונים (מנשה)', 'location':'', 'engName':' AVNEY CHAIM - EMUNIM'},
    {'hebName':'אבנני קאסם', 'location':'', 'engName':'AVNEI KASEM'},
    {'hebName':'אגרו גנים ', 'location':'', 'engName':'AGRO GANIM'},
    {'hebName':'אדם', 'location':'526278009', 'engName':'AWTAM'},
    {'hebName':'אהרוני ת"א', 'location':'', 'engName':'AHRONI'},
    {'hebName':'אטיאס', 'location':'', 'engName':'ATEAC'},
    {'hebName':'איברהים - שואפת', 'location':'052-4086841', 'engName':'IBRAHIM'},
    {'hebName':'אייל - יזהר מושב ישרש', 'location':'', 'engName':'EYAL'},
    {'hebName':'איילון חגי', 'location':'', 'engName':'AYALON'},
    {'hebName':'איציק כרמינה', 'location':'', 'engName':''},
    {'hebName':'איציק קרמונה', 'location':'', 'engName':'ECIK KAREMONA'},
    {'hebName':"אל חוראני - ג'לג'וליה", 'location':'', 'engName':'EL CHORANI'},
    {'hebName':'אלגים רחובות', 'location':'', 'engName':'ELGIM REHOVOT'},
    {'hebName':'אליקוס', 'location':'', 'engName':'ELIKOHS'},
    {'hebName':'אלכס', 'location':'', 'engName':'ALEKS'},
    {'hebName':"אמג'ד - בית צפפא", 'location':'', 'engName':'AMJAD '},
    {'hebName':"אמג'ד - קאסם", 'location':'', 'engName':'AMJAD'},
    {'hebName':'אמיגד גלגוליה', 'location':'050-5200468', 'engName':'AMJAD'},
    {'hebName':'אמיר  - טייבה', 'location':'050-05895416', 'engName':'AMIR - TAYBE'},
    {'hebName':'אנואר   חיים', 'location':'', 'engName':'ANUAR'},
    {'hebName':'אסי - בית צפפא', 'location':'', 'engName':'ASI'},
    {'hebName':'אפרדוס - גבעה צרפתית  ', 'location':'052-1771468', 'engName':'AFERDOS'},
    {'hebName':'אקראם - טירה', 'location':'', 'engName':'AKRAM'},
    {'hebName':'ארבע עונות - תלפיות', 'location':'052-5478025', 'engName':'ARBA ONOT'},
    {'hebName':'ארמון בחול', 'location':'', 'engName':'AREMON BAHOLL'},
    {'hebName':'אשקלון', 'location':'גולן 0577783355', 'engName':'ASHGELON'},
    {'hebName':"באסאם - ג'לג'וליה", 'location':'', 'engName':'BASAM'},
    {'hebName':'באקרי - בית צפפא', 'location':'', 'engName':'BAKRI'},
    {'hebName':'בדיר - קאסם', 'location':'', 'engName':'BADIR - KASEM'},
    {'hebName':'בונסאי שופ', 'location':'', 'engName':'BONSAI SHOP'},
    {'hebName':'בועז', 'location':'', 'engName':'BOAZ'},
    {'hebName':'ביר אלמכסור ', 'location':'523821322', 'engName':'BER AELEMAKESOR'},
    {'hebName':'בית וגן  בני', 'location':'', 'engName':'BIED VGAN'},
    {'hebName':'ברושים - (אזור מסובים)', 'location':'', 'engName':'BROSHIM'},
    {'hebName':'ברזני', 'location':'', 'engName':'BARAZHNI'},
    {'hebName':"ג'אלאל / היימאן - אורנית", 'location':'', 'engName':'JALAL'},
    {'hebName':"ג'אמאל - חיזמה", 'location':'', 'engName':'JAMAL'},
    {'hebName':'ג"ומעה פתח תיקוה', 'location':'', 'engName':'GOMEAH'},
    {'hebName':'גבעת ברנר', 'location':'', 'engName':'GIVAT BRENNER'},
    {'hebName':'גולד - רחובות', 'location':'', 'engName':'GOLD'},
    {'hebName':'גינון האחים', 'location':'', 'engName':'GINUN HAACHIM'},
    {'hebName':'גינון ונטיעות', 'location':'', 'engName':'GINUN VENETIOT'},
    {'hebName':'גליריה', 'location':'', 'engName':''},
    {'hebName':'גן העיר', 'location':'', 'engName':'GAN HWER'},
    {'hebName':'גן טרופי', 'location':'', 'engName':'GAN TEROPI'},
    {'hebName':'גן ירק', 'location':'', 'engName':'GAN YARAK'},
    {'hebName':'גני אמין  - ב"ש', 'location':'', 'engName':'GANEY AMIN- SHAKKER'},
    {'hebName':'גני הצבי', 'location':'', 'engName':'GANEY HATZVI'},
    {'hebName':'גרין גן - ב"ש', 'location':'', 'engName':'GREEN GAN'},
    {'hebName':'גרסיאני - בית חנן', 'location':'', 'engName':'GRASIANI'},
    {'hebName':'דוגמאות', 'location':'', 'engName':'DOGEMA'},
    {'hebName':'דוגמאות', 'location':'', 'engName':''},
    {'hebName':'דוריאן - ב"ש', 'location':'', 'engName':'DORIYAN'},
    {'hebName':'דחליל  -  ', 'location':'', 'engName':' DACHLIL'},
    {'hebName':'דחליל  -  ', 'location':'', 'engName':' DACHLIL'},
    {'hebName':'דניאל היימן יד בינימין', 'location':'', 'engName':'DENIAEL HAYMAN'},
    {'hebName':'דרום השרון', 'location':'', 'engName':'DROM HASHARON'},
    {'hebName':'דרך ארץ', 'location':'', 'engName':'DEREK  AEREZ'},
    {'hebName':'דרך המשי', 'location':'', 'engName':'DERECH HAMESHI'},
    {'hebName':'האירוסים', 'location':'', 'engName':'HAIROZEM'},
    {'hebName':'האמר / בדיר', 'location':'', 'engName':'HAMER'},
    {'hebName':'האני ', 'location':'חיזמה 0525889848', 'engName':'HANNI'},
    {'hebName':'הגבעה הירוקה חולון', 'location':'', 'engName':'AGIVA AYERUKA'},
    {'hebName':'הגן הקסום - גת רימון', 'location':'', 'engName':'AGAN AKASUM'},
    {'hebName':'הגן הקסום - דניאל', 'location':'', 'engName':'AGAN AKASUM'},
    {'hebName':'הגן הקסום ציוןן', 'location':'', 'engName':'HGN HKASOHM CEUON'},
    {'hebName':'הדר נוי', 'location':'', 'engName':'ADAR NOY'},
    {'hebName':'החוויה ', 'location':'', 'engName':'HAVHYA'},
    {'hebName':'החצר של אורלי', 'location':'050-2772212', 'engName':'ORLI'},
    {'hebName':'הכפר הירוק - רמי', 'location':'', 'engName':'AKFAR AYAROK'},
    {'hebName':'הכרמל', 'location':'', 'engName':'HAKARMEL'},
    {'hebName':'הסוכה הירוקה', 'location':'', 'engName':'HASOKA HYEROKA'},
    {'hebName':'הסחלב ראשל"צ', 'location':'', 'engName':'HASACHLAV '},
    {'hebName':'הפרח בגני - סאלח', 'location':'', 'engName':'APERACH BEGANI'},
    {'hebName':'הר טוב', 'location':'', 'engName':'HAR TOB'},
    {'hebName':'השביל הירוק', 'location':'', 'engName':'ASHVIL AYAROK'},
    {'hebName':'השתיל מושב תדהר', 'location':'', 'engName':'AHSHTIL'},
    {'hebName':"וואעל  - ג'לג'וליה", 'location':'', 'engName':'WAEL '},
    {'hebName':'וודעה - שער השלום ', 'location':'', 'engName':'SHAHAR HASHALOM'},
    {'hebName':'וונדי - עד הלום ', 'location':'', 'engName':'WENDY AD HALOM'},
    {'hebName':'וונדי עין ורד', 'location':'', 'engName':'WENDY EIN VERED'},
    {'hebName':'וונדי שילת ', 'location':'', 'engName':'WENDY SHILAT'},
    {'hebName':'ויקטור', 'location':'', 'engName':'VIKTOR'},
    {'hebName':'זיעד - גבעת זאב', 'location':'', 'engName':'ZIAD '},
    {'hebName':'זיעד אבו אחמד צומת אלמוג', 'location':'צומת אלמוג', 'engName':'ZIAD ABU  ACHMAD'},
    {'hebName':'חאדר - ביתר עילית', 'location':'', 'engName':'CHADER'},
    {'hebName':'חאלה - טירה', 'location':'', 'engName':'HALA'},
    {'hebName':'חי וצומח', 'location':'דימונה', 'engName':''},
    {'hebName':'חיזקיה', 'location':'', 'engName':'HZEKEYA'},
    {'hebName':'חנותא', 'location':'050-5561866', 'engName':'CHANUTA'},
    {'hebName':'חנן אשקלון', 'location':'', 'engName':'CHANAN ASHKELON'},
    {'hebName':'טיפטוף - ב"ש', 'location':'', 'engName':'TIFTUF'},
    {'hebName':'טרוייה', 'location':'', 'engName':'TEROYA'},
    {'hebName':'יאסר', 'location':'', 'engName':'YASER'},
    {'hebName':'יארין - דלת אל כרמל', 'location':'', 'engName':'YARIN DALYAT EL KARMEL'},
    {'hebName':'יונאס  0525557544', 'location':'', 'engName':'YONAS'},
    {'hebName':'יוקה', 'location':'', 'engName':'YUKA'},
    {'hebName':'יחייא -שייח גראח', 'location':'', 'engName':'YICHIYA'},
    {'hebName':'יניב אדריכלות נוף - גבעולים', 'location':'', 'engName':'YANIV GIVOLIM'},
    {'hebName':'יניב אוזן  - מושב ניר עקיבא', 'location':'', 'engName':'YANIV UZAN'},
    {'hebName':'יפה נוף', 'location':'', 'engName':'YEFE NOF'},
    {'hebName':'ירוק בהיר', 'location':'', 'engName':'YAROK BAHIR'},
    {'hebName':'ירוק ישראלי', 'location':'', 'engName':'YAROK ISRAELI'},
    {'hebName':'ירוק עד', 'location':'רמת השרון', 'engName':'YAROK AD'},
    {'hebName':'ירוק עד', 'location':'', 'engName':'YAROK AD'},
    {'hebName':'ירקונים -  רפי', 'location':'', 'engName':'YARKONIM'},
    {'hebName':'כדורי - ב"ש', 'location':'', 'engName':'KADURI'},
    {'hebName':'כחול ישראלי', 'location':'', 'engName':'KACHOL ISRAELI'},
    {'hebName':'כפר מנדה', 'location':'', 'engName':'KFAR MANDA'},
    {'hebName':'לאקיה', 'location':'', 'engName':'LAKYA'},
    {'hebName':"לב הארץ - ג'לג'וליה", 'location':'', 'engName':'LEV AHARETS'},
    {'hebName':'לביא - הרצליה', 'location':'', 'engName':'LAVIE'},
    {'hebName':'ליעות ', 'location':'', 'engName':'LIOT'},
    {'hebName':"מאהדי - ג'לג'וליה", 'location':'', 'engName':'MAHADI'},
    {'hebName':'מאיר שפורן', 'location':'', 'engName':'MEAER SHEPORAN'},
    {'hebName':'מודעין קבלן - ירוק בהיר', 'location':'', 'engName':'YAROK BAHIR'},
    {'hebName':'מודעין קבלן - ירוק בהיר', 'location':'', 'engName':'MOHTEHN'},
    {'hebName':'מוחמד גבעת זאב', 'location':'', 'engName':'MUCHAMAD '},
    {'hebName':'מוחמד יאסר - חיזמה', 'location':'', 'engName':'MUCHAMAD YASER '},
    {'hebName':'מונטאסר - חיזמה', 'location':'חיזמה', 'engName':'MONTASER'},
    {'hebName':"מוסטפא - ג'לג'וליה", 'location':'', 'engName':'MUSTAFA'},
    {'hebName':'מוראד מישור אדומים', 'location':'', 'engName':'MORAD '},
    {'hebName':'מורדי מרמלשטיין', 'location':'', 'engName':'MARMELSHTEIN'},
    {'hebName':'מסובים', 'location':'', 'engName':'MESUBIM'},
    {'hebName':'משה ברזני מבשרת', 'location':'', 'engName':'MOSHE BARAZANI'},
    {'hebName':'משמר השבעה', 'location':'', 'engName':'MISEWMAR HASIVEAH'},
    {'hebName':'משתלת אורן -אשדוד ', 'location':'052-6249093 דרור', 'engName':'OREN - ASHDOD'},
    {'hebName':'משתלת בית זית - דני', 'location':'', 'engName':'BEIT ZAIT'},
    {'hebName':'משתלת הבית יקי - בית שמש', 'location':'', 'engName':'YAKI'},
    {'hebName':'משתלת הגליל', 'location':'', 'engName':'MASETELAT HAGALELL'},
    {'hebName':'משתלת ההר', 'location':'אבוגוש', 'engName':'HAHR'},
    {'hebName':'משתלת הכפר - אחמד ', 'location':'שאקר - קאסם', 'engName':'AKFAR ACHMAD'},
    {'hebName':'משתלת חלא טירה', 'location':'', 'engName':'HALA'},
    {'hebName':'נאדאל פחורי - חיזמה', 'location':'', 'engName':'NADAL FACHURI'},
    {'hebName':'נאדר ', 'location':'חיזמה 0522250993', 'engName':'NADER'},
    {'hebName':'נווה ירק  - עופר ', 'location':'', 'engName':'NEVE YARAK'},
    {'hebName':'נווה מדבר מושב יד נתן', 'location':'', 'engName':'NEVE MIDBAR'},
    {'hebName':'נופר', 'location':'', 'engName':'NOFAR'},
    {'hebName':'נופר מודעין', 'location':'', 'engName':'NOFAR MODEIN'},
    {'hebName':'ניירובי - שילת', 'location':'', 'engName':'NIROBI'},
    {'hebName':'נס הרים', 'location':'054-5782817', 'engName':'NES HARIM'},
    {'hebName':'נפתלי - מושב גן חיים', 'location':'', 'engName':'NAFTALI'},
    {'hebName':'נצני עוז משק 66', 'location':'', 'engName':'NIZANEY OZ'},
    {'hebName':'נקודת חן', 'location':'', 'engName':'NEKUDAT CHEN'},
    {'hebName':'נרדי - תלפיות', 'location':'', 'engName':'NARDI'},
    {'hebName':'נתניה', 'location':'', 'engName':'NATANYA'},
    {'hebName':'סאמיר צומת אלמוג', 'location':'', 'engName':'SAMIR '},
    {'hebName':'סול גלזר  - בית שמש', 'location':'', 'engName':'SOL GLAZER'},
    {'hebName':'סחנין', 'location':'', 'engName':'SACHNIN'},
    {'hebName':'סנסן - גבעת זאב', 'location':'', 'engName':'SANSAN GIVAT ZEHEV'},
    {'hebName':'סנסן - תלפיות', 'location':'איברהים', 'engName':'SANSAN'},
    {'hebName':"עבד - ג'לג'וליה", 'location':'', 'engName':'ABED'},
    {'hebName':'עדי - ב"ש', 'location':'', 'engName':' ADI'},
    {'hebName':'עדל - גבעה צרפתית', 'location':'', 'engName':'ADEL'},
    {'hebName':'עודד', 'location':'', 'engName':'HOTET'},
    {'hebName':'עוואז - ביתר עילית', 'location':'', 'engName':'AWAZ'},
    {'hebName':'עוואז מהדי', 'location':'', 'engName':'AWAZ MAHADI'},
    {'hebName':"עומאר - ג'לג'וליה", 'location':'', 'engName':'UMAR'},
    {'hebName':'עונות השנה', 'location':'', 'engName':'ONOT HASHANA'},
    {'hebName':'עותמאן - בית צפפא', 'location':'', 'engName':'OTMAN'},
    {'hebName':'עזיזי אחזקות', 'location':'', 'engName':'AZIZI'},
    {'hebName':'עידו - גאליה', 'location':'', 'engName':'IDO'},
    {'hebName':'עין עירון', 'location':'', 'engName':'EIN IRON'},
    {'hebName':'עיסמאייל - ביתר עילית', 'location':'', 'engName':'ISMAIL'},
    {'hebName':'על הדרך - ראשל"צ', 'location':'', 'engName':'AL ADERECH'},
    {'hebName':"עלה  עומאר - ג'לג'וליה", 'location':'', 'engName':'ALLA UMAR'},
    {'hebName':'עליזה מושב מבקיעים', 'location':'', 'engName':'ALIZA MAVKEIM'},
    {'hebName':"עמאר - ג'לג'וליה", 'location':'', 'engName':'AMAR'},
    {'hebName':'ענן הכרמל', 'location':'', 'engName':'ENAN'},
    {'hebName':'עפוד', 'location':'', 'engName':'APUD'},
    {'hebName':"עפוד - ג'לג'וליה", 'location':'', 'engName':'APUD'},
    {'hebName':'עץ הצפון', 'location':'', 'engName':'ETZ AZAFON'},
    {'hebName':'עץ השדה ', 'location':'', 'engName':'HEC ASADE'},
    {'hebName':'פארס -   ריחן', 'location':'', 'engName':'FARES '},
    {'hebName':'פואד - טירה', 'location':'', 'engName':'FUAD'},
    {'hebName':'פואד עוסיפייה', 'location':'', 'engName':'FUAD OSFIYA'},
    {'hebName':'פוטוס הרצליה', 'location':'', 'engName':'FOTUS'},
    {'hebName':'פולאק מסילת ציון', 'location':'', 'engName':'POLAK'},
    {'hebName':'פורם שתיל - ב"ש', 'location':'', 'engName':'FORM SHETIL'},
    {'hebName':'פירחי שיר', 'location':'', 'engName':'PIRCHEY SHIR'},
    {'hebName':'פסיפלורה', 'location':'', 'engName':'PASIFLORA'},
    {'hebName':"פרדוס- ג'לג'וליה", 'location':'50-3247947', 'engName':'PARDUS'},
    {'hebName':'פרח וגן', 'location':'', 'engName':''},
    {'hebName':'פרחים במשתלה - אשדוד  ', 'location':'', 'engName':'PRACHIM BAMASHTELA'},
    {'hebName':'פתאל  ת"א', 'location':'', 'engName':'FATAEL'},
    {'hebName':'צומת השלום - מאהר  ', 'location':'', 'engName':'MAHER'},
    {'hebName':"קאיד- ג'לג'וליה", 'location':"אמג'ד ", 'engName':'KAID'},
    {'hebName':'קאמל - אריאל', 'location':'', 'engName':'KAMEL - ARIEL'},
    {'hebName':'קדימה', 'location':'', 'engName':'GADEMA'},
    {'hebName':'קוקטייל - חנה', 'location':'', 'engName':'KOKTEIL'},
    {'hebName':"ראשיד - ג'לג'וליה", 'location':'', 'engName':'RASHID'},
    {'hebName':'רביבו דודו - אמונים', 'location':'', 'engName':'REVIVO'},
    {'hebName':'רגב', 'location':'בית אלעזרי', 'engName':'REGEV'},
    {'hebName':'רהט - איברהים', 'location':'', 'engName':'RAHAT IBRAHEIM'},
    {'hebName':' עודה / אחמד-רהט', 'location':'', 'engName':'RAHAT - ACHMAD / UDA'},
    {'hebName':'רוזמרין - טייבה', 'location':'', 'engName':'ROZMARIN'},
    {'hebName':'רוני יהלום', 'location':'', 'engName':'RONI YAHALOM'},
    {'hebName':'רונן', 'location':'505350122', 'engName':'RONEN'},
    {'hebName':'רונן שיווק הצריף', 'location':'', 'engName':'SHIVUK ATSRIF'},
    {'hebName':'רחובות - עזרא', 'location':'', 'engName':'RECHOVOT'},
    {'hebName':'שאהר - המשתלה הירוקה ', 'location':'', 'engName':'SHAHER'},
    {'hebName':"שאנטי - ג'לג'וליה", 'location':'', 'engName':'SHANTI'},
    {'hebName':'שאקר', 'location':'', 'engName':'SHAKER'},
    {'hebName':'שאקר פארס', 'location':'', 'engName':'SHAKER FARES'},
    {'hebName':'שאראף - חיזמה', 'location':'', 'engName':'SHARAF'},
    {'hebName':'שדות', 'location':'', 'engName':'SADOT'},
    {'hebName':'ששון רעננה', 'location':'', 'engName':'SASON'},
    {'hebName':'שתולים יוקה', 'location':'', 'engName':'SHTULIM'},
    {'hebName':'שתיל וצמח', 'location':'505369360', 'engName':'SWTIL WASEMAH'},
    {'hebName':'תגל הארץ', 'location':'', 'engName':'TAGEL HAARETZ'},
    {'hebName':'תמיר - ירוק בעיניים', 'location':'', 'engName':'TAMIR'}
  ]
}

module.exports = data
